<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>
    
    <ul class="nav nav-tabs nav-justified hidden-xs">
        <li class="<?php echo $tab_1_active; ?>"><a href="#tab1" data-toggle="tab">Cabildos</a></li>
        <li class="<?php echo $tab_2_active; ?>"><a href="#tab2" data-toggle="tab">Acciones de Exigibilidad de derechos</a></li>       
        <li class="<?php echo $tab_3_active; ?>"><a href="#tab3" data-toggle="tab">Iniciativas empresariales</a></li> 
        <!-- <li class="<?php echo $tab_4_active; ?>"><a href="#tab4" data-toggle="tab">Transferencias presupuestales</a></li>  -->
        <!--<li class="<?php echo $tab_4_active; ?>"><a href="#tab4" data-toggle="tab">Fuente(s) de la información</a></li>--> 
    </ul>
    <ul class="nav nav-tabs nav-justified visible-xs">    
        <li class="tab-pane <?php echo $tab_1_active; ?>"><a href="#tab1" data-toggle="tab">Cabildos</a></li>
        <li class="tab-pane <?php echo $tab_2_active; ?>"><a href="#tab2" data-toggle="tab">Acciones de Exigibilidad de derechos</a></li>        
        <li class="tab-pane <?php echo $tab_3_active; ?>"><a href="#tab3" data-toggle="tab">Iniciativas empresariales</a></li>
        <!-- <li class="tab-pane <?php echo $tab_4_active; ?>"><a href="#tab4" data-toggle="tab">Transferencias presupuestales</a></li> -->
        <!--<li class="tab-pane <?php echo $tab_4_active; ?>" ><a href="#tab4" data-toggle="tab">Fuente(s) de la información</a></li>-->
    </ul>
    
    <div class="tab-content"> 
        <div class="tab-pane <?php echo $tab_1_active; ?>" id="tab1">
        <div class="row">
                 <div class="col-md-12">
                     <?php View::partial('gestion_territorial/cabildo/editar', false, 
            array('array_validacion_cabildo'=>$array_validacion_cabildo, 'cabildos'=>$cabildos, 
                'obj_territorio'=>$obj_territorio, 'key'=>$key, 'sub_tab'=>$sub_tab,
                'order'=>$order, 'page'=>$page)); ?>  
                 </div>
             </div>
            <div class="row">
                 <div class="col-md-6">
                 <label for="panel_jei">Jurisdicción especial indígena</label>
                    <div id="panel_jei" class="panel panel-default">
                        <div class="panel-body">
                            <div class="col-md-12">
                                <div class="row">
                                    <?php echo DwForm::hidden('jurisdiccion_especial_indigena.territorio_id', NULL, $obj_territorio->id) ?>
                                    <?php echo DwForm::hidden('jurisdiccion_especial_indigena.id', NULL, NULL) ?>
                                    <div class="col-md-12">
                                    <?php echo DwForm::select('jurisdiccion_especial_indigena.tiene_reglamento', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, '¿Tiene reglamento de jurisdicción especial indígena?'); ?>
                                    </div>
                                </div>
                                <div id="div_se_aplica_reglamento" class="row">
                                    <div class="col-md-12">
                                    <?php echo DwForm::select('jurisdiccion_especial_indigena.se_aplica_reglamento', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, '¿Se aplica el reglamento?'); ?>
                                    </div>
                                </div>
                                <div id="div_descripcion_aplicacion" class="row">
                                    <div class="col-md-12">
                                    <?php echo DwForm::textarea('jurisdiccion_especial_indigena.descripcion_aplicacion_reglamento', array('class'=>'input-lower'), NULL, 'Descripción de la aplicación del reglamento'); ?>
                                    </div>
                                </div>
                                
                                    </div>
                            </div>
                        </div>
                    </div> 
                <script type='text/javascript'>
        $('#div_se_aplica_reglamento').hide();
        $('#div_descripcion_aplicacion').hide();
        
         if($('#jurisdiccion_especial_indigena_tiene_reglamento').val() == 'SI')
        { 
            $('#div_se_aplica_reglamento').show();
            //$('#div_descripcion_aplicacion').show();
        }else{$('#div_se_aplica_reglamento').hide();
                $('#div_descripcion_aplicacion').hide();
                
        }
              
              if($('#jurisdiccion_especial_indigena_se_aplica_reglamento').val() == 'SI')
        { 
            //$('#div_se_aplica_reglamento').show();
            $('#div_descripcion_aplicacion').show();
        }else{//$('#div_se_aplica_reglamento').hide();
                $('#div_descripcion_aplicacion').hide();}
              
       
        $("#jurisdiccion_especial_indigena_tiene_reglamento").change(
        function(){
                var si_no 	=	$('#jurisdiccion_especial_indigena_tiene_reglamento').val();
                if( si_no == 'SI')
                    {
                        $('#div_se_aplica_reglamento').show();
                        //$('#div_descripcion_aplicacion').show();
                    }
                    else
                    {
                        $('#div_se_aplica_reglamento').hide();
                        $('#div_descripcion_aplicacion').hide();
                        $('#jurisdiccion_especial_indigena_se_aplica_reglamento').val('');
                        $('#jurisdiccion_especial_indigena_descripcion_aplicacion_reglamento').val('');
                    }

        });
        
         $("#jurisdiccion_especial_indigena_se_aplica_reglamento").change(
        function(){
                var si_no 	=	$('#jurisdiccion_especial_indigena_se_aplica_reglamento').val();
                if( si_no == 'SI')
                    {
                        //$('#div_se_aplica_reglamento').show();
                        $('#div_descripcion_aplicacion').show();
                    }
                    else
                    {
                        //$('#div_se_aplica_reglamento').hide();
                        $('#div_descripcion_aplicacion').hide();
                        $('#jurisdiccion_especial_indigena_descripcion_aplicacion_reglamento').val('');
                    }

        });
        
        
</script>
                <div class="col-md-6">
                 <label for="panel_pdv">Plan de vida</label>
                    <div id="panel_pdv" class="panel panel-default">
                        <div class="panel-body">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-12">
                                    <?php                                    
                                    echo DwForm::hidden('plan_de_vida.territorio_id', NULL, $obj_territorio->id) ?>
                                        <?php echo DwForm::hidden('plan_de_vida.id', NULL, NULL) ?>
                                    <?php echo DwForm::select('plan_de_vida.tiene_plan', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, '¿Tiene plan de vida?'); ?>
                                    </div>
                                </div>
                                 <div class="row">
                                     <div id="div_se_aplica_plan" class="col-md-12">
                                    <?php echo DwForm::select('plan_de_vida.se_aplica_plan', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, '¿Se aplica el plan de vida?'); ?>
                                    </div>
                               </div>                            
                                
                                    </div>
                            </div>
                        </div>
                    </div>
<script type="text/javascript">
    $('#div_se_aplica_plan').hide();
    if($('#plan_de_vida_tiene_plan').val()=='SI')
        {
            $('#div_se_aplica_plan').show();
        }
        else
        {
            $('#div_se_aplica_plan').hide();
        }
    
 $("#plan_de_vida_tiene_plan").change(
        function(){
                var si_no 	=	$('#plan_de_vida_tiene_plan').val();
                if( si_no == 'SI')
                    {
                        //$('#div_se_aplica_reglamento').show();
                        $('#div_se_aplica_plan').show();
                    }
                    else
                    {
                        //$('#div_se_aplica_reglamento').hide();
                        $('#div_se_aplica_plan').hide();
                        $('#plan_de_vida_se_aplica_plan').val('');
                    }

        });
</script>
             </div>                
            
              <div class="row">
            <div class="form-actions">
                 <div class="text-right">
                     <?php echo DwForm::send('Actualizar megaproyecto'); ?>
                    <?php echo DwButton::back($url_redir_back); ?>                    
                </div>
            </div>
        </div>
    </div>
        
<!--      //////////////////////////////////  SEGUNDA PESTAÑA-->
 <div class="tab-pane <?php echo $tab_2_active; ?>" id="tab2">
            <div class="row">
                 <div class="col-md-12">
                     <?php View::partial('gestion_territorial/accion_exigibilidad_derecho/editar', false, 
            array('accion_exigibilidad_derechos'=>$accion_exigibilidad_derechos, 
                'obj_territorio'=>$obj_territorio, 'key'=>$key, 'sub_tab'=>$sub_tab,
                'order'=>$order, 'page'=>$page, 'controller'=>$controller)); ?>  
                 </div>
             </div>
                 <!-- FIN TABULACION INTERNA  -->                
              <div class="form-actions">
                 <div class="text-right">
                    <?php echo DwButton::back($url_redir_back); ?>                    
                </div>
            </div>
    </div> 


<!--      //////////////////////////////////  TERCERA PESTAÑA-->

 <div class="tab-pane <?php echo $tab_3_active; ?>" id="tab3">
            <!-- TABULACION INTERNA  -->
    <div class="row">
                 <div class="col-md-12">
                     <?php View::partial('gestion_territorial/iniciativa_empresarial/editar', false, 
            array('iniciativa_empresarials'=>$iniciativa_empresarials, 
                'obj_territorio'=>$obj_territorio, 'key'=>$key, 'sub_tab'=>$sub_tab,
                'order'=>$order, 'page'=>$page, 'controller'=>$controller)); ?>  
                 </div>
             </div>
                 <!-- FIN TABULACION INTERNA  -->                
              <div class="form-actions">
                 <div class="text-right">
                    <?php echo DwButton::back($url_redir_back); ?>                    
                </div>
            </div>
    </div> 






    <?php echo DwForm::close(); ?> 
        </div>
    
    
    <script type='text/javascript'>
//        
//         if($('#megaproyecto_es_filial_matriz').val() == 'SI')
//        { $('#div_megaproyecto_nombre_filial_matriz').show();
//        }else{$('#div_megaproyecto_nombre_filial_matriz').hide();}
//              
//       
//        $("#megaproyecto_es_filial_matriz").change(
//        function(){
//                var si_no 	=	$('#megaproyecto_es_filial_matriz').val();
//                if( si_no == 'SI')
//                    {
//                        //$('#megaproyecto_nombre_filial_matriz').show();
//                        $('#div_megaproyecto_nombre_filial_matriz').show();                   
//                        $('#megaproyecto_nombre_filial_matriz').focus(); 
//                    }
//                    else
//                    {
//                       $('#div_megaproyecto_nombre_filial_matriz').hide();
//                       $('#megaproyecto_nombre_filial_matriz').val('');
//                    }
//
//        });
        
        
</script>
