<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

        <div class="row">
            <div class="col-md-12">
                <label for="panel_info_basica"><h3 class="panel-title">Información básica</h3></label>                
               <div id="panel_info_basica" class="panel panel-default">
                  <div class="panel-body">
                   <div class="row">
                    <div class="col-md-4">
                        <?php echo DwForm::text('departamento.nombre', array('class'=>'input-required'), NULL, 'Nombre'); ?>
                    </div>
                        <div class="col-md-4">
                            <?php echo DwForm::text('departamento.capital', array('class'=>'input-required'), NULL, 'Capital'); ?>
                        </div>
                        <div class="col-md-4">
                            <?php echo DwForm::text('departamento.cant_municipio', array('class'=>'input-lower input-integer input-required'), NULL, 'Cantidad de municipios'); ?>
                        </div>
                    </div>                    
                    <div class="row">                       
                        <div class="col-md-4">
                            <?php echo DwForm::text('departamento.cant_municipio_pacifico', array('class'=>'input-integer input-required'), NULL, 'Cantidad de municipios en el pacífico'); ?>
                        </div>
                        <div class="col-md-4">
                            <?php echo DwForm::date('departamento.fecha_creacion', array('class'=>'input-required'), '', 'Fecha de creación del departamento'); ?>
                        </div> 
                    </div>  
                      <div class="row">
                           <div class="col-md-12">
                            <label for="panel_area">Area superficie</label>
                            <div id="panel_area" class="panel panel-default">
                                <div class="panel-body">
                                  <div class="row">
                                    <div class="col-md-4">
                                        <label for="departamento_area_total">Total<span class="req">*</span></label>
                                     <div class="form-group">
                                        <div class="input-group">                                 
                                            <input id="departamento_area_total" name="departamento[area_total]" type="text" value="" class="formato_punto_coma form-control" required="required" data-invalid="">                                          
                                          <div class="input-group-addon">Km<sup>2</sup></div>                                          
                                        </div>
                                      </div>
                                    </div>
                                      <div class="col-md-4">
                                        <label for="departamento_area_urbana">Urbana<span class="req">*</span></label>
                                     <div class="form-group">
                                        <div class="input-group">                                 
                                            <input id="departamento_area_urbana" name="departamento[area_urbana]" type="text" value="" class="formato_punto_coma form-control" required="required" data-invalid="">                                          
                                          <div class="input-group-addon">Km<sup>2</sup></div>                                          
                                        </div>
                                      </div>
                                    </div>
                                     <div class="col-md-4">
                                        <label for="departamento_area_rural">Rural<span class="req">*</span></label>
                                     <div class="form-group">
                                        <div class="input-group">                                 
                                            <input id="departamento_area_rural" name="departamento[area_rural]" type="text" value="" class="formato_punto_coma form-control" required="required" data-invalid="">                                          
                                          <div class="input-group-addon">Km<sup>2</sup></div>                                          
                                        </div>
                                      </div>
                                    </div>
                                  </div>                                    
                                </div>
                            </div>
                           
                        </div>
                          
                      </div>
                       
                  </div>
               </div>
            </div>
                
         <div class="col-md-12">
                 <label for="panel_poblacion"><h3 class="panel-title">Población</h3></label>   
                <div id="panel_poblacion" class="panel panel-default">
                  <div class="panel-body">
                       
               <?php  echo View::partial('poblacion/agregar', false, array('para_territorio' => 'no')); ?>   
                                  
                  </div>
               </div>
            </div>   
            <div class="col-md-12">               
               <label for="panel_fuente"><h3 class="panel-title">Fuente(s) de la información</h3></label>               
                 <div id="panel_fuente" class="panel panel-default">
                     <div class="panel-body">
                        <?php View::partial('fuentes/agregar', false, NULL); ?>
                    </div>                    
                </div>
            </div> 
           
                          
                    
        </div>                        

        <div class="row">
            <div class="form-actions">                   
                <?php echo DwForm::send('Guardar departamento'); ?>
                <?php echo DwForm::cancel('observatorio/departamentos/listar'); ?>
                <?php echo DwForm::focus('departamento.nombre'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?> 
</div>

<script type="text/javascript">
     $(".formato_punto_coma").priceFormat(
        {
            prefix: '',
            centsLimit: 2,
            centsSeparator: ',',
            thousandsSeparator: '.'
        });   
    
        
$("#form-1").submit(function(){
    $(".formato_punto").priceFormat(
    {
        prefix: '',
        centsLimit: 0,
        centsSeparator: '',
        thousandsSeparator: ''
    });    
});
</script>