<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions">
                <?php echo DwHtml::button("observatorio/departamentos/agregar/", 'agregar', array('class' => 'btn-success'), 'fa-check-square-o', APP_AJAX); ?>
            </div>            
        </div>
    </div>

    <div class="container-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive datatable">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th data-search="nombre" data-order="nombre">NOMBRE</th>                    
                    <th class="col-hidden" data-search="cant_subregion_reg" data-order="cant_subregion_reg">SUBREGIONES</th>
                    <th class="col-hidden" data-search="cant_municipio_reg" data-order="cant_municipio_reg">MUNICIPIOS</th>
                    <th class="col-hidden" data-order="cant_territorio_reg">TERRITORIOS</th>
                    <th class="col-hidden" data-order="cant_territorio_comunidad_negra">TERRITORIOS COMUNIDAD NEGRA</th>
                    <th class="col-hidden" data-order="cant_territorio_indigena">TERRITORIOS INDIGENA</th>                    
                    <th class="btn-actions col-blocked text-center">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php $num = 1; ?>
                <?php foreach($departamentos as $departamento): ?>
                    <?php $key_show = Security::setKey($departamento->id, 'show_departamento'); ?>
                    <?php $key_upd = Security::setKey($departamento->id, 'upd_departamento'); ?>
                    <?php $key_inac = Security::setKey($departamento->id, 'inactivar_departamento'); ?>
                    <?php $key_reac = Security::setKey($departamento->id, 'reactivar_departamento'); ?>
                    <tr>
                        <td><?php echo $num++; ?></td>
                        <td><?php echo $departamento->nombre; ?></td>
                        <td><?php echo $departamento->cant_subregion_reg; ?></td>
                        <td><?php echo $departamento->cant_municipio_reg; ?></td>
                        <td><?php echo $departamento->cant_territorio_reg; ?></td>
                        <td><?php echo $departamento->cant_territorio_comunidad_negra; ?></td>
                        <td><?php echo $departamento->cant_territorio_indigena; ?></td>                        
                        <td class="btn-actions">
                            <?php echo DwHtml::buttonTable('Ver departamento', "observatorio/departamentos/ver/$key_show/", null, 'info', 'fa-eye'); ?>
                            <?php echo DwHtml::buttonTable('Modificar departamento', "observatorio/departamentos/editar/$key_upd/", null, 'warning', 'fa-edit'); ?>                            
                            <?php echo DwHtml::buttonTable('Agregar municipio', "observatorio/municipios/agregar/$departamento->id/$departamento->nombre", null, 'success', 'fa-plus'); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>