<div class="col-md-12">
                            <label for="panel_ubicacion_proyecto">Ubicación <?php echo $titulo; ?></label>
                            <div id="panel_ubicacion_proyecto" class="panel panel-default">
                                <div class="panel-body">
                            
                      
                                    <div id="div_ubicaciones" class="container-overflow">
                         
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>DEPARTAMENTO</th>
                    <th>SUBREGION</th>
                    <th>MUNICIPIO</th>                    
                    <th>TERRITORIO</th>                                                          
                </tr>
            </thead>
            <tbody>                
                <?php
                 
                $contador_ubicacion = 1;
                foreach($ubicaciones as $ubicacion):                  
                    
                        ?>
                        <tr>                       
                        <td><?php echo $ubicacion->departamento; ?></td>
                        <td><?php if($ubicacion->subregion){echo $ubicacion->subregion;}else{echo 'Sin información';} ?></td>
                        <td><?php echo $ubicacion->municipio; ?></td>                        
                        <td><?php echo $ubicacion->territorio; ?></td>                       
                    </tr>
                                  
                    <?php $contador_ubicacion++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
                      
                                </div>
                            </div>                           
                        </div>  