                 <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions">                
                <?php echo DwHtml::button("gestion_territorial/$controller/agregar_accion_exigibilidad_derecho/$obj_territorio->id/$obj_territorio->nombre/$key/$order/$page/", 'agregar acción de exigibilidad de derecho', array('class' => 'btn-success'), 'fa-check-square-o', APP_AJAX); ?>                   
            </div>            
        </div>
    </div>                   
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th>TIPO DE ACCIÓN</th>
                    <th>FECHA INICIO ACCIÓN</th>                                        
                    <th>LA ACCIÓN HA TERMINADO</th>
                    <th>FECHA TERMINÓ ACCIÓN</th>
                    <th class="btn-actions text-center">ESTADO</th>
                    <th class="btn-actions col-blocked text-center">OPCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $contador_accion_exigibilidad_derecho = 1;
                foreach($accion_exigibilidad_derechos as $accion_exigibilidad_derecho): ?>                    
                    <?php //$key_show = Security::setKey($accion_exigibilidad_derecho->id, 'show_accion_exigibilidad_derecho'); ?>
                    <?php $key_upd = Security::setKey($accion_exigibilidad_derecho->id, 'upd_accion_exigibilidad_derecho'); ?>                    
                    <?php $key_del = Security::setKey($accion_exigibilidad_derecho->id, 'del_accion_exigibilidad_derecho'); ?>                    
                    <tr>
                        <td><?php echo $contador_accion_exigibilidad_derecho; ?></td>                        
                        <td><?php echo $accion_exigibilidad_derecho->accion_exigibilidad; ?></td>
                        <td><?php echo $accion_exigibilidad_derecho->fecha_accion_inicio; ?></td>
                        <td><?php echo $accion_exigibilidad_derecho->accion_termino; ?></td>
                        <td><?php echo $accion_exigibilidad_derecho->fecha_accion_termino; ?></td>
                         <td class="btn-actions"><?php View::partial('nivel_estado/ver', false, array('nivel'=>$accion_exigibilidad_derecho->nivel, 'estado'=>$accion_exigibilidad_derecho->estado)); ?>
                        <td class="btn-actions">
                            <?php View::partial('opcion/ver', false, 
                                    array('elemento'=>'acción de exigibilidad derecho',
                                        "nombre"=>$accion_exigibilidad_derecho->accion_exigibilidad,
                                        "url_ver"=>NULL,
                                        "url_editar"=>"gestion_territorial/$controller/editar_accion_exigibilidad_derecho/$key_upd/$key/$order/$page/",
                                        "url_eliminar"=>"gestion_territorial/$controller/eliminar_accion_exigibilidad_derecho/$accion_exigibilidad_derecho->accion_exigibilidad/$obj_territorio->nombre/$key_del/$key/$order/$page/")); ?>
                        </td>
<!--                        <td class="btn-actions">                            
                            <?php echo DwHtml::buttonTable('Modificar acción exigibilidad derecho', "gestion_territorial/$controller/editar_accion_exigibilidad_derecho/$key_upd/$key/$order/$page/", null, 'warning', 'fa-edit'); ?>                              
                        </td>-->
                    </tr>
                    <?php $contador_accion_exigibilidad_derecho++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
<br>