<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

               <div class="row">
                    <div class="col-md-12">
                        <?php echo DwForm::hidden('conflicto.territorio_id', NULL, $territorio_id) ?>
                        <?php echo DwForm::text('conflicto.nombre', array('class'=>'input-lower input-required'), NULL, 'Nombre del conflicto.'); ?>
                    </div>                
<!--                    <div class="col-md-6">
                        <?php echo DwForm::select('conflicto.conflicto', array(''=>'Seleccione', 'INTRAETNICO'=>'INTRAETNICO', 'INTERETNICO'=>'INTERETNICO'), array('class'=>'input-required'), NULL, 'Conflicto'); ?>
                    </div>           -->
                </div>
    
            
        <div class="row">
                     <div class="col-md-12">
                 <label for="panel_poblacion"><h3 class="panel-title">Tipo de conflicto</h3></label>   
                <div id="panel_poblacion" class="panel panel-default">
                  <div class="panel-body">
                       <div class="row">
                        <div class="col-md-4">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('conflicto.intra_etnico', '1', NULL, NULL, 'INTRAETNICO'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('conflicto.inter_etnico', '1', NULL, NULL, 'INTERETNICO'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('conflicto.cultural', '1', NULL, NULL, 'CULTURAL'); ?>
                                </div>
                            </div>   
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('conflicto.economico', '1', NULL, NULL, 'ECONÓMICO'); ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">                             
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('conflicto.recurso_natural', '1', NULL, NULL, 'RECURSOS NATURALES'); ?>
                                </div>
                            </div>
                           
                             <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('conflicto.politico_violencia', '1', NULL, NULL, 'POLÍTICO - VIOLENCIA'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('conflicto.politico_grupo_armado', '1', NULL, NULL, 'POLÍTICO - PRESENCIA DE GRUPOS ARMADOS'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('conflicto.politico_electoral', '1', NULL, NULL, 'POLÍTICO - ELECTORAL'); ?>
                                </div>
                            </div> 
                        </div>   
                        <div class="col-md-4">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('conflicto.territorial_uso', '1', NULL, NULL, 'TERRITORIAL - USO'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('conflicto.territorial_delimitacion', '1', NULL, NULL, 'TERRITORIAL - DELIMITACIÓN'); ?>
                                </div>
                            </div>
                             <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('conflicto.otro', '1', NULL, NULL, 'OTROS'); ?>
                                </div>
                            </div> 
                                                
                        </div>                     
                    </div>  
                                      
                  </div>
               </div>
            </div>
            
</div>
    
    <label for="panel_politico"><h3 class="panel-title">Descripción del conflicto</h3></label>   
                <div id="panel_politico" class="panel panel-default">
                  <div class="panel-body">
    <div class="row">
        <div class="col-md-6">
            <?php echo DwForm::textarea('conflicto.hechos', array('class'=>'input-lower input-required'), NULL, 'Hechos'); ?>
        </div>
         <div class="col-md-6">
            <?php echo DwForm::textarea('conflicto.actores', array('class'=>'input-lower input-required'), NULL, 'Actores'); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?php echo DwForm::textarea('conflicto.ubicacion', array('class'=>'input-lower input-required'), NULL, 'Ubicación'); ?>
        </div>
        <div class="col-md-6">
            <?php echo DwForm::textarea('conflicto.observacion', array('class'=>'input-lower'), NULL, 'Observaciones'); ?>
        </div>
    </div>
                  </div>
                </div>
     <div class="row">
        <div class="col-md-4">
            <?php echo DwForm::select('conflicto.estado_conflicto', array(''=>'Seleccione', 'ABIERTO'=>'ABIERTO', 'CERRADO'=>'CERRADO'), array('class'=>'input-required'), NULL, 'Estado del conflicto'); ?>
        </div>
        <div class="col-md-4">
            <?php echo DwForm::date('conflicto.fecha_comienzo', array('class'=>'input-required'), '', 'Fecha comienzo conflicto'); ?>
        </div>
        <div class="col-md-4">
            <?php echo DwForm::date('conflicto.fecha_fin', array('class'=>''), '', 'Fecha terminación conflicto'); ?>
        </div>
    </div>

        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Guardar conflicto'); ?>
                <?php echo DwForm::cancel($url_redir_back); ?>
                <?php echo DwForm::focus('conflicto.nombre'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
