<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process_estado_nivel('comunidad', $obj_comunidad, $page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

               <div class="row">
                    <div class="col-md-6">
                        <?php echo DwForm::hidden('comunidad.territorio_id', NULL, $obj_comunidad->territorio_id) ?>
                        <?php echo DwForm::hidden('comunidad.id', NULL, $obj_comunidad->id) ?>
                        <?php echo DwForm::text('comunidad.nombre', array('class'=>'input-lower input-required'), $obj_comunidad->nombre, 'Nombre del barrio'); ?>
                    </div>                
                    <div class="col-md-6">
                        
                    </div>                     
                </div>
            <div class="row">
            <div class="form-actions">
               <?php echo DwForm::send('Actualizar barrio'); ?>
                <?php echo DwForm::cancel($url_redir_back); ?>
                <?php echo DwForm::focus('comunidad.nombre'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
