<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>          
        <div class="row">                    
            <div class="col-md-6">                         
                <?php echo DwForm::hidden('territorio.tipo', NULL, 'comunidad_negra') ?>
                <?php echo DwForm::dbSelect('territorio.muncipio_id', 'nombre', array('observatorio/municipio', 'getListadoMunicipioDBS'), NULL, array('class'=>'input-required'), NULL, 'Seleccione el Municipio'); ?>                    
            </div>
            <div class="col-md-6">  
                <?php echo DwForm::text('territorio.nombre', array('class'=>'input-required'), NULL, 'Nombre del territorio'); ?>                        
            </div>                     
        </div>         
        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::sendContinue('Continuar'); ?>
                <?php echo DwForm::cancel(); ?>
                <?php echo DwForm::focus('territorio.nombre'); ?>
            </div>
        </div>
    </div>  

    <?php echo DwForm::close(); ?>

</div>
