<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>          
                <div class="row">                    
                    <div class="col-md-6">                         
                        <?php echo DwForm::hidden('territorio.tipo', NULL, 'comunidad_negra') ?>
                        <?php echo DwForm::hidden('territorio.departamento_nombre', NULL, '') ?>
                        <?php echo DwForm::text('territorio.nombre', array('class'=>'input-required'), NULL, 'Nombre del territorio'); ?>
                    </div>
                     <div class="col-md-6">  
                         <?php echo DwForm::select('territorio.titulado', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>'input-required'), NULL, '¿El territorio está titulado?:'); ?>
                    </div>                     
                </div>                
           
                <div class="row">
                    <div class="col-md-12">
                <label for="panel_departamento"><h5>Seleccione el departamento al cual pertenece el territorio</h5></label>
                            <div id="panel_departamento" class="panel panel-default">
                                <div class="panel-body">                                    
                                         <div class="col-md-3">
<!--                <div class="btn-group btn-group-justified" role="group" aria-label="Justified button group">
                <?php foreach($departamentos as $departamento): ?>
                    <?php echo Ajax::link("observatorio/genericos/db_check_municipios/$departamento->id/$departamento->nombre", $departamento->nombre, "div_municipios", "btn btn-default", array('role'=>'button') );?>                                                      
                    
                <?php endforeach; ?>
                </div>-->
       <?php echo DwForm::dbSelect('select.departamento_id', 'nombre', array('observatorio/departamento', 'getListadoDepartamentoDBS'), NULL, array('class'=>'input-required'), NULL, 'Departamento'); ?>
          <?php //echo DwForm::dbSelect('select.departamento_id', 'nombre', array('observatorio/departamento', 'getListadoDepartamentoDBS', Departamento::ACTIVO), NULL, array('class'=>'input-required'), NULL, 'Departamento'); ?>
               </div>
                <div class="col-md-9">
                    <div id="div_municipios"></div>
                </div>
                                    
                                </div>
            </div>
                </div>
                    </div>
                   
               
            
              <div class="row">
            <div class="form-actions">
                <?php echo DwForm::sendContinue('Continuar'); ?>
                <?php echo DwForm::cancel(); ?>
                <?php echo DwForm::focus('territorio.nombre'); ?>
            </div>
        </div>
    </div>  

    <?php echo DwForm::close(); ?>
<script type='text/javascript'>
$("#select_departamento_id").change(function(){
	var regiones_id 	=	$('#select_departamento_id').val();
        var departamento_id 	=	$('#select_departamento_id').val();
        //var departamento_nombre =	$('#select_departamento_id').attr('id');
        
        var departamento_nombre = $("#select_departamento_id option:selected").text();  
        $('#territorio_departamento_nombre').val(departamento_nombre);
        var titulo_panel        =       'Seleccione el (los) municipio(s) al cual pertenece el territorio';
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_check_municipios/'; ?>"+departamento_id+"/"+departamento_nombre+"/"+titulo_panel+"/",
          async: true,
          data: "regiones_id=" + regiones_id,
          success: function(html){
            $("#div_municipios").html(html);
          }
        });
});
</script>

</div>
