<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

               <div class="row">
                    <div class="col-md-6">
                        <?php echo DwForm::hidden('subsidio.megaproyecto_id', NULL, $megaproyecto_id) ?>
                        <?php echo DwForm::text('subsidio.nombre', array('class'=>'input-required'), NULL, 'Nombre del subsidio'); ?>
                    </div>                
                    <div class="col-md-6">
                        <?php echo DwForm::select('subsidio.consulta_previa', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>'input-required'), NULL, '¿Son un compromiso de la Consulta Previa?'); ?>
                    </div>           
                </div>
    
    
    <div class="row">
        <div class="col-md-6">        
           <?php echo DwForm::dbSelect('subsidio.tipo_subsidio_id', 'nombre', array('opcion/tipo_subsidio', 'getListadoTipoSubsidioDBS', TipoSubsidio::ACTIVO), NULL, array('class'=>'input-required'), NULL, 'Tipo de subsidio'); ?>
        </div>
        <div class="col-md-6">
            <?php echo DwForm::textarea('subsidio.descripcion', array('class'=>'input-lower'), '', 'Descripción del subsidio'); ?>
        </div>
    </div>
    
     <div class="row">
            <div class="col-md-6">
                <?php echo DwForm::number('subsidio.monto', array('class'=>'input-lower input-integer input-required'), NULL, 'Monto del subsidio'); ?>            
            </div>
                      
        </div>    

        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Guardar subsidio'); ?>
                <?php echo DwForm::cancel($url_redir_back); ?>
                <?php //echo DwForm::focus('subsidio.nombre'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
