<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>
    
    <ul class="nav nav-tabs hidden-xs">
        <li class="<?php echo $tab_1_active; ?>"><a href="#tab1" data-toggle="tab">Información general</a></li>
        <li class="<?php echo $tab_2_active; ?>"><a href="#tab2" data-toggle="tab">Vinculación de la población</a></li>
        <li class="<?php echo $tab_3_active; ?>"><a href="#tab3" data-toggle="tab">Daños</a></li>
        <li class="<?php echo $tab_4_active; ?>"><a href="#tab4" data-toggle="tab">Desarrollo Normativo</a></li>
        <li class="<?php echo $tab_5_active; ?>"><a href="#tab5" data-toggle="tab">Política Pública</a></li>
        <li class="<?php echo $tab_6_active; ?>"><a href="#tab6" data-toggle="tab">Acciones de seguimiento y control</a></li>
        <li class="<?php echo $tab_7_active; ?>"><a href="#tab7" data-toggle="tab">Fuente(s)</a></li>
    </ul>
    <ul class="nav nav-tabs visible-xs">
        <li class="tab-pane <?php echo $tab_1_active; ?>"><a href="#tab1" data-toggle="tab">Información general</a></li>
        <li class="tab-pane <?php echo $tab_2_active; ?>"><a href="#tab2" data-toggle="tab">Vinculación de la población</a></li>
        <li class="tab-pane <?php echo $tab_3_active; ?>"><a href="#tab3" data-toggle="tab">Daños</a></li>
        <li class="tab-pane <?php echo $tab_4_active; ?>"><a href="#tab4" data-toggle="tab">Desarrollo Normativo</a></li>
        <li class="tab-pane <?php echo $tab_5_active; ?>"><a href="#tab5" data-toggle="tab">Política Pública</a></li>
        <li class="tab-pane <?php echo $tab_6_active; ?>"><a href="#tab6" data-toggle="tab">Acciones de seguimiento y control</a></li>
        <li class="tab-pane <?php echo $tab_7_active; ?>"><a href="#tab7" data-toggle="tab">Fuente(s)</a></li>
    </ul>
    
    <div class="tab-content"> 
        <div class="tab-pane fade <?php echo $tab_1_active; ?>" id="tab1">
        <div class="row">
            <div class="col-md-12">
                <label for="panel_info_basica"><h3 class="panel-title">Información básica</h3></label>                
               <div id="panel_info_basica" class="panel panel-default">
                  <div class="panel-body">
                   <div class="row">
                    <div class="col-md-12">
                        <?php echo DwForm::hidden('megaproyecto.clase_megaproyecto', NULL, $megaproyecto->clase_megaproyecto) ?>
                        <?php echo DwForm::text('megaproyecto.nombre', array('class'=>'input-readonly'), $megaproyecto->nombre, 'Nombre'); ?>
                    </div>                      
                    </div>
                      <div class="row">    
         <?php 
            if($megaproyecto->documento != '')
            {              
                echo '<div class="col-md-9">';                        
                echo '<a id="enlace_documento_megaproyecto" class="btn btn-info" target="_blank" href="'.PUBLIC_PATH.'files/upload/megaproyecto/'.$megaproyecto->documento.'">';
                echo '<i class="fa fa-pd-expand fa-eye"></i>Ver documento adjunto</a>';                            
                echo '</div>';                      
            }
         ?>
     </div>
                      
                      <div class="row">
                           <div class="col-md-12">
                            <label for="panel_tipo_proyecto">Tipo de megaproyecto</label>
                            <div id="panel_tipo_proyecto" class="panel panel-default">
                                <div class="panel-body">
                                   
                      <div class="row">
                           <div class="col-md-6">
                        <?php echo DwForm::dbSelect('megaproyecto.tipo_megaproyecto_id', 'nombre', array('opcion/tipo_megaproyecto', 'getTipoMegaproyectoByClaseMegaproyectoDBS', $clase_megaproyecto), NULL, array('class'=>'input-readonly'), $megaproyecto->tipo_megaproyecto_id, 'Seleccione el tipo de megaproyecto'); ?>                        
                    </div>  
                           <div id="div_subtipo_megaproyecto" class="col-md-6">
                        <?php echo DwForm::dbSelect('megaproyecto.subtipo_megaproyecto_id', 'nombre', array('opcion/subtipo_megaproyecto', 'getSubtipoMegaproyectoByTipoMegaproyectoIdDBS', $megaproyecto->tipo_megaproyecto_id ), NULL, array('class'=>'input-readonly'), $megaproyecto->subtipo_megaproyecto_id, 'Seleccione el Sub tipo de megaproyecto'); ?>                        
                    </div>   
                      </div>
                      
                      <div class="row">
                          <?php echo DwForm::hidden("megaproyecto.micro_subtipo_megaproyecto_id", NULL, NULL);?> 
                          <div id="div_micro_subtipo_megaproyecto" class="col-md-12">
                        <?php echo DwForm::dbRadioId('micro_subtipo_megaproyecto','nombre',array('opcion/micro_subtipo_megaproyecto', 'getMicroSubtipoMegaproyectoByTipoMegaproyectoIdDBS', $megaproyecto->subtipo_megaproyecto_id), array('onclick'=>'myFunction(this.value)', 'onclick'=>'return false'), $megaproyecto->micro_subtipo_megaproyecto_id); ?>
                    </div>   
                      </div>
                                </div>
                            </div>                           
                        </div>                          
                      </div>
                      
                      
                       <div class="row">
                           <?php View::partial('ubicacion/ver', false, array('ubicaciones'=>$ubicaciones, 'titulo'=>'del megaproyecto')); ?>  
                      </div>
                      <div class="row">
                    <div class="col-md-12">
                        <?php echo DwForm::textarea('megaproyecto.descripcion', array('class'=>'input-readonly'), NULL, 'Descripción del megaproyecto'); ?>
                    </div>                
                    </div>                    
                    
                      <div class="row">
                           <div class="col-md-12">
                            <label for="panel_area">Área del proyecto</label>
                            <div id="panel_area" class="panel panel-default">
                                <div class="panel-body">
                                  <div class="row">
                                    <div class="col-md-6">
                                        <label for="megaproyecto_area_terrestre">Terrestre</label>
                                     <div class="form-group">
                                        <div class="input-group">                                 
                                            <input readonly="readonly" id="megaproyecto_area_terrestre" name="megaproyecto[area_terrestre]" type="text" value="<?php echo number_format($megaproyecto->area_terrestre, 2, ',', '.'); ?>" class="form-control input-readonly" data-invalid="">                                          
                                          <div class="input-group-addon">Km<sup>2</sup></div>                                          
                                        </div>
                                      </div>
                                    </div>
                                      <div class="col-md-6">
                                        <label for="megaproyecto_area_maritima">Marítima</label>
                                     <div class="form-group">
                                        <div class="input-group">                                 
                                            <input readonly="readonly" id="megaproyecto_area_maritima" name="megaproyecto[area_maritima]" type="text" value="<?php echo number_format($megaproyecto->area_maritima, 2, ',', '.'); ?>" class="form-control input-readonly" data-invalid="">                                          
                                          <div class="input-group-addon">Km<sup>2</sup></div>                                          
                                        </div>
                                      </div>
                                    </div>
                                    
                                  </div>                                    
                                </div>
                            </div>                           
                        </div>                          
                      </div>
                      
                      <div class="row">                       
                        <div class="col-md-6">
                            <?php echo DwForm::date('megaproyecto.fecha_iniciacion', array('class'=>'input-readonly'), $megaproyecto->fecha_iniciacion, 'Fecha de iniciación del proyecto'); ?>
                        </div> 
                        <div class="col-md-6">
                            <?php echo DwForm::date('megaproyecto.fecha_terminacion', array('class'=>'input-readonly'), $megaproyecto->fecha_terminacion, 'Fecha de terminación del proyecto'); ?>
                        </div> 
                    </div>  
                      
                       <div class="row">
                           <div class="col-md-12">
                            <label for="panel_empresa">Empresa propietaria del proyecto</label>
                            <div id="panel_empresa" class="panel panel-default">
                                <div class="panel-body">
                                  <div class="row">
                                      <div class="col-md-6">
                        <?php echo DwForm::text('megaproyecto.nombre_empresa', array('class'=>'input-readonly'), $megaproyecto->nombre_empresa, 'Nombre de la empresa'); ?>
                    </div>
                                      <div class="col-md-3">
                        <?php echo DwForm::text('megaproyecto.representante_empresa', array('class'=>'input-readonly'), $megaproyecto->representante_empresa, 'Nombre del representante legal'); ?>
                    </div>       
                                      <div class="col-md-3">
                        <?php echo DwForm::text('megaproyecto.sede_principal', array('class'=>'input-readonly'), $megaproyecto->sede_principal, 'Sede principal'); ?>
                    </div>           
                                    
                                  </div>  
                                    <div class="row">                                                                 
                                        <div class="col-md-6">  
                         <?php echo DwForm::text('megaproyecto.es_filial_matriz', array('class'=>'input-readonly'), $megaproyecto->es_filial_matriz, '¿La empresa es filial de una casa matriz?:'); ?>
                    </div>  
                                        <div id="div_megaproyecto_nombre_filial_matriz" class="col-md-6">
                        <?php echo DwForm::text('megaproyecto.nombre_filial_matriz', array('class'=>'input-readonly'), $megaproyecto->nombre_filial_matriz, 'Nombre de la casa matriz'); ?>
                    </div>
                                    
                                  </div> 
                                    <div class="row">                                                                 
                                        <div class="col-md-6">  
                         <?php echo DwForm::text('megaproyecto.accionista_nacional', array('class'=>'input-readonly'), $megaproyecto->accionista_nacional, '¿La empresa tiene accionistas Nacionales?:'); ?>
                    </div>  
                                        <div class="col-md-6">
                        <?php echo DwForm::text('megaproyecto.accionista_extranjero', array('class'=>'input-readonly'), $megaproyecto->accionista_extranjero, '¿La empresa tiene accionistas Extranjeros?:'); ?>
                    </div>
                                    
                                  </div> 
                                    <div class="row">                                                                 
                                        <div class="col-md-6">  
                         <?php echo DwForm::text('megaproyecto.otro_sitio_colombia', array('class'=>'input-readonly'), $megaproyecto->otro_sitio_colombia, '¿La empresa opera en otro sitio en Colombia?:'); ?>
                    </div>  
                                        <div class="col-md-6">
                        <?php echo DwForm::text('megaproyecto.otro_sitio_extranjero', array('class'=>'input-readonly'), $megaproyecto->otro_sitio_extranjero, '¿La empresa opera en otro sitio en el Extranjero?:'); ?>
                    </div>
                                    
                                  </div> 
                                    
                                    <div class="row">
                    <div class="col-md-6">                        
                        <?php echo DwForm::text('megaproyecto.otra_actividad', array('class'=>'input-readonly'), $megaproyecto->otra_actividad, '¿La empresa realiza otras actividades?'); ?>
                    </div>                       
                                        <div id="div_megaproyecto_otra_actividad_cual" class="col-md-6">
                         <?php echo DwForm::textarea('megaproyecto.otra_actividad_cual', array('class'=>'input-readonly'), $megaproyecto->otra_actividad_cual, 'Cuáles actividades'); ?>
                    </div> 
                    </div> 
                                </div>
                            </div>                           
                        </div>                          
                      </div>
                      
                      <div id="div_financiacion_proyecto" class="row">
                           <div class="col-md-12">
                            <label for="panel_financiacion">Financiación del proyecto</label>
                            <div id="panel_financiacion" class="panel panel-default">
                                <div class="panel-body">
                                  <div class="row"><div class="col-md-2">
                        <?php echo DwForm::select('megaproyecto.moneda_monto_inversion', array(''=>'- SELECCIONE -', '$' => '$ - PESOS', 'US' => 'US - DOLARES', '€' => '€ - EUROS'), array('class' => 'input-readonly'), NULL, 'Moneda monto de inversión') ?>   
                    </div>
                    <div class="col-md-4">
                        <?php echo DwForm::number('megaproyecto.monto_inversion', array('class'=>'input-readonly input-money'), number_format($megaproyecto->monto_inversion, 2, '.', ','), 'Monto de inversión'); ?>
                    </div>
                                     
                                    
                                  </div>  
                                    <div class="row">                                                                 
                                        <div class="col-md-6">  
                         <?php echo DwForm::text('megaproyecto.financia_nacional_publica', array('class'=>'input-readonly'), $megaproyecto->financia_nacional_publica, '¿Es financiado por instituciones nacionales públicas?:'); ?>
                    </div>  
                                        <div id="div_megaproyecto_financia_nacional_publica_cual" class="col-md-6">
                        <?php echo DwForm::textarea('megaproyecto.financia_nacional_publica_cual', array('class'=>'input-readonly'), $megaproyecto->financia_nacional_publica_cual, '¿Cuáles instituciones finaciadoras nacionales públicas?'); ?>
                    </div>
                                    
                                  </div> 
                                   <div class="row">                                                                 
                                        <div class="col-md-6">  
                         <?php echo DwForm::text('megaproyecto.financia_nacional_privada', array('class'=>'input-readonly'), $megaproyecto->financia_nacional_privada, '¿Es financiado por instituciones nacionales privadas?:'); ?>
                    </div>  
                                       <div id="div_megaproyecto_financia_nacional_privada_cual" class="col-md-6">
                        <?php echo DwForm::textarea('megaproyecto.financia_nacional_privada_cual', array('class'=>'input-readonly'), $megaproyecto->financia_nacional_privada_cual, '¿Cuáles instituciones finaciadoras nacionales privadas?'); ?>
                    </div>
                                    
                                  </div> 
                                    <div class="row">                                                                 
                                        <div class="col-md-6">  
                         <?php echo DwForm::text('megaproyecto.financia_inter_publica', array('class'=>'input-readonly'), $megaproyecto->financia_inter_publica, '¿Es financiado por instituciones internacionales públicas?:'); ?>
                    </div>  
                                        <div id="div_megaproyecto_financia_inter_publica_cual" class="col-md-6">
                        <?php echo DwForm::textarea('megaproyecto.financia_inter_publica_cual', array('class'=>'input-readonly'), $megaproyecto->financia_inter_publica_cual, '¿Cuáles instituciones finaciadoras internacionales públicas?'); ?>
                    </div>
                                    
                                  </div> 
                                    
                                    <div class="row">                                                                 
                                        <div class="col-md-6">  
                         <?php echo DwForm::text('megaproyecto.financia_inter_privada', array('class'=>'input-readonly'), $megaproyecto->financia_inter_privada, '¿Es financiado por instituciones internacionales privadas?:'); ?>
                    </div>  
                                        <div id="div_megaproyecto_financia_inter_privada_cual" class="col-md-6">
                        <?php echo DwForm::textarea('megaproyecto.financia_inter_privada_cual', array('class'=>'input-readonly'), $megaproyecto->financia_inter_privada_cual, '¿Cuáles instituciones finaciadoras internacionales privadas?'); ?>
                    </div>
                                    
                                  </div> 
                                </div>
                            </div>                           
                        </div>                          
                      </div>
                      
                      <div id="div_cesion" class="row">
                    <div class="col-md-3">                        
                        <?php echo DwForm::text('megaproyecto.cesion', array('class'=>'input-readonly'), $megaproyecto->cesion, '¿Cesión?'); ?>
                    </div>                       
                           <div id="div_megaproyecto_tipo_cesion" class="col-md-3">
                          <?php echo DwForm::text('megaproyecto.tipo_cesion', array('class'=>'input-readonly'), $megaproyecto->tipo_cesion, '¿Tipo de cesión?'); ?>
                    </div> 
                           <div id="div_megaproyecto_nuevo_titular_empresa" class="col-md-6">
                        <?php echo DwForm::text('megaproyecto.nuevo_titular_empresa', array('class'=>'input-readonly'), $megaproyecto->nuevo_titular_empresa, 'Nombre del nuevo titular'); ?>
                    </div>
                           
                    </div> 
                       
                  </div>
               </div>
            </div>             
        </div> 
            <div class="row">
            <div class="form-actions">
                <div class="text-left">
                     <?php echo DwButton::back($url_redir_back); ?>                     
                </div>
            </div>
        </div>
    </div>
        
<!--      //////////////////////////////////  SEGUNDA PESTAÑA-->
 <div class="tab-pane fade <?php echo $tab_2_active; ?>" id="tab2">
            
                 <!-- TABULACION INTERNA  -->
    <?php View::partial('vinculacion_poblacion/ver', false, 
            array('empleos'=>$empleos, 'megaproyecto'=>$megaproyecto, 'key'=>$key, 'sub_tab'=>$sub_tab,
                'programa_sociales'=>$programa_sociales, 'subsidios'=>$subsidios)); ?>  
                 <!-- FIN TABULACION INTERNA -->
                
              <div class="form-actions">
                <div class="text-left">
                     <?php echo DwButton::back($url_redir_back); ?>                     
                </div>
            </div>
    </div> 


<!--      //////////////////////////////////  TERCERA PESTAÑA-->

 <div class="tab-pane fade <?php echo $tab_3_active; ?>" id="tab3">
            <!-- TABULACION INTERNA  -->
    <?php View::partial('afectacion/ver', false, 
            array('territorios_afectados'=>$territorios_afectados, 'megaproyecto'=>$megaproyecto, 'key'=>$key, 'sub_tab'=>$sub_tab)); ?>  
                 <!-- FIN TABULACION INTERNA -->
              <div class="form-actions">
                <div class="text-left">
                     <?php echo DwButton::back($url_redir_back); ?>                     
                </div>
            </div>
    </div> 


<!--      //////////////////////////////////  CUARTA PESTAÑA-->

 <div class="tab-pane fade <?php echo $tab_4_active; ?>" id="tab4">
             <div class="row">
                 <div class="col-md-12">
                     <?php View::partial('accion_seguimiento_control/ver', false, 
            array('accion_seguimiento_controls'=>$accion_seguimiento_controls, 'megaproyecto'=>$megaproyecto, 'key'=>$key, 'sub_tab'=>$sub_tab)); ?>  
                 
                 </div>
             </div>
              <div class="row">
            <div class="form-actions">
                 <?php echo DwButton::back($url_redir_back); ?>
            </div>
        </div>
    </div>



<!--      //////////////////////////////////  QUINTA PESTAÑA-->
        <div class="tab-pane fade <?php echo $tab_5_active; ?>" id="tab5">
             <div class="row">
                 <div class="col-md-12">
                     <?php View::partial('fuentes/ver', false, array('fuentes'=>$fuentes)); ?>  
                 </div>
             </div>
              <div class="row">
            <div class="form-actions">
                <div class="text-left">
                    <?php echo DwButton::back(); ?>                    
                </div>
            </div>
        </div>
    </div> 

    <?php echo DwForm::close(); ?> 
        </div>
    </div>
    
    <script type='text/javascript'>
        //$(document).ready(function() {
        $("#megaproyecto_monto_inversion").priceFormat(
        {
            prefix: '',
            centsLimit: 2,
            centsSeparator: '.',
            thousandsSeparator: ','
        });
        //});
        
         //Para extraccion pesquera
            if($('#megaproyecto_tipo_megaproyecto_id').val() == '14')
            {
                $("#div_financiacion_proyecto").hide();
                $("#div_cesion").hide();
            }
            else
            {
                $("#div_financiacion_proyecto").show();
                $("#div_cesion").show();
            }
            
            
            
         if($('#megaproyecto_es_filial_matriz').val() == 'SI')
        { $('#div_megaproyecto_nombre_filial_matriz').show();
        }else{$('#div_megaproyecto_nombre_filial_matriz').hide();}
              
       
        $("#megaproyecto_es_filial_matriz").change(
        function(){
                var si_no 	=	$('#megaproyecto_es_filial_matriz').val();
                if( si_no == 'SI')
                    {
                        //$('#megaproyecto_nombre_filial_matriz').show();
                        $('#div_megaproyecto_nombre_filial_matriz').show();                   
                        $('#megaproyecto_nombre_filial_matriz').focus(); 
                    }
                    else
                    {
                       $('#div_megaproyecto_nombre_filial_matriz').hide();
                       $('#megaproyecto_nombre_filial_matriz').val('');
                    }

        });
        
        
        if($('#megaproyecto_otra_actividad').val() == 'SI')
        { $('#div_megaproyecto_otra_actividad_cual').show();
        }else{$('#div_megaproyecto_otra_actividad_cual').hide();}
              
        $("#megaproyecto_otra_actividad").change(
        function(){
                var si_no 	=	$('#megaproyecto_otra_actividad').val();
                if( si_no == 'SI')
                    {                        
                        $('#div_megaproyecto_otra_actividad_cual').show();                   
                        $('#megaproyecto_otra_actividad_cual').focus(); 
                    }
                    else
                    {
                       $('#div_megaproyecto_otra_actividad_cual').hide();
                       $('#megaproyecto_otra_actividad_cual').val('');
                    }

        });
        
        
       
        if($('#megaproyecto_financia_nacional_publica').val() == 'SI')
        { $('#div_megaproyecto_financia_nacional_publica_cual').show();
        }else{$('#div_megaproyecto_financia_nacional_publica_cual').hide();}
        
        
        $("#megaproyecto_financia_nacional_publica").change(
        function(){
                var si_no 	=	$('#megaproyecto_financia_nacional_publica').val();
                if( si_no == 'SI')
                    {                        
                        $('#div_megaproyecto_financia_nacional_publica_cual').show();                   
                        $('#megaproyecto_financia_nacional_publica_cual').focus(); 
                    }
                    else
                    {
                       $('#div_megaproyecto_financia_nacional_publica_cual').hide();
                       $('#megaproyecto_financia_nacional_publica_cual').val('');
                    }

        });
        
        
        if($('#megaproyecto_financia_inter_publica').val() == 'SI')
        { $('#div_megaproyecto_financia_inter_publica_cual').show();
        }else{$('#div_megaproyecto_financia_inter_publica_cual').hide();}
        
        $("#megaproyecto_financia_inter_publica").change(
        function(){
                var si_no 	=	$('#megaproyecto_financia_inter_publica').val();
                if( si_no == 'SI')
                    {                        
                        $('#div_megaproyecto_financia_inter_publica_cual').show();                   
                        $('#megaproyecto_financia_inter_publica_cual').focus(); 
                    }
                    else
                    {
                       $('#div_megaproyecto_financia_inter_publica_cual').hide();
                       $('#megaproyecto_financia_inter_publica_cual').val('');
                    }

        });
        
         if($('#megaproyecto_financia_nacional_privada').val() == 'SI')
            { $('#div_megaproyecto_financia_nacional_privada_cual').show();
            }else{$('#div_megaproyecto_financia_nacional_privada_cual').hide();}
                
        $("#megaproyecto_financia_nacional_privada").change(
        function(){
                var si_no 	=	$('#megaproyecto_financia_nacional_privada').val();
                if( si_no == 'SI')
                    {                        
                        $('#div_megaproyecto_financia_nacional_privada_cual').show();                   
                        $('#megaproyecto_financia_nacional_privada_cual').focus(); 
                    }
                    else
                    {
                       $('#div_megaproyecto_financia_nacional_privada_cual').hide();
                       $('#megaproyecto_financia_nacional_privada_cual').val('');
                    }

        });
        
        if($('#megaproyecto_financia_inter_privada').val() == 'SI')
            { $('#div_megaproyecto_financia_inter_privada_cual').show();
            }else{$('#div_megaproyecto_financia_inter_privada_cual').hide();}
            
        $("#megaproyecto_financia_inter_privada").change(
        function(){
                var si_no 	=	$('#megaproyecto_financia_inter_privada').val();
                if( si_no == 'SI')
                    {                        
                        $('#div_megaproyecto_financia_inter_privada_cual').show();                   
                        $('#megaproyecto_financia_inter_privada_cual').focus(); 
                    }
                    else
                    {
                       $('#div_megaproyecto_financia_inter_privada_cual').hide();
                       $('#megaproyecto_financia_inter_privada_cual').val('');
                    }

        });
        

        if($('#megaproyecto_cesion').val() == 'SI')
        { $('#div_megaproyecto_nuevo_titular_empresa').show();
           $('#div_megaproyecto_tipo_cesion').show(); 
        }else{$('#div_megaproyecto_nuevo_titular_empresa').hide();
        $('#div_megaproyecto_tipo_cesion').hide();}
        
       
        $("#megaproyecto_cesion").change(
        function(){
                var si_no 	=	$('#megaproyecto_cesion').val();
                if( si_no == 'SI')
                    {                        
                        $('#div_megaproyecto_tipo_cesion').show();                                            
                        $('#megaproyecto_tipo_cesion').focus();
                    }
                    else
                    {
                       $('#div_megaproyecto_tipo_cesion').hide();
                       $('#div_megaproyecto_nuevo_titular_empresa').hide();
                       $('#megaproyecto_nuevo_titular_empresa').val('');
                    }

        });
        
              
        $("#megaproyecto_tipo_cesion").change(
        function()
        {                          
            $('#div_megaproyecto_nuevo_titular_empresa').show(); 
            $('#megaproyecto_nuevo_titular_empresa').focus(); 
        });
        
        
</script>
