<?php DwForm::open() ?>

<?php
if ($objeto->nivel == '1') //1=PUBLICO, 2=PRIVADO
{
    //echo DwHtml::buttonTable('Privatizar', "", null, 'default', 'fa-lock').'&nbsp;';  
    echo '<button title="Pasar a privado" id="btn_privado" type="button" class="btn btn-default btn-xs">
            <i class="btn-icon-only fa fa-lock"></i>
            </button>&nbsp;';
} else {
    //echo DwHtml::buttonTable('Publicar', "", null, 'default', 'fa-unlock').'&nbsp;';
    echo '<button title="Pasar a público" id="btn_publico" type="button" class="btn btn-default btn-xs">
            <i class="btn-icon-only fa fa-unlock"></i>
            </button>&nbsp;';
}
if ($objeto->estado == '2') //1=BORRADOR, 2=COMPLETADO
{
    //echo DwHtml::buttonTable('Borrador', "", null, 'default', 'fa-eraser').'&nbsp;';
    echo '<button title="Pasar a borrador" id="btn_borrador" type="button" class="btn btn-default btn-xs">
            <i class="btn-icon-only fa fa-eraser"></i>
            </button>';
} else {
    //echo DwHtml::buttonTable('Completar', "", null, 'default', 'fa-check').'&nbsp;';
    echo '<button title="Pasar a completo" id="btn_completo" type="button" class="btn btn-default btn-xs">
            <i class="btn-icon-only fa fa-check"></i>
            </button>';
}
?>
<?php
echo ($objeto->nivel == '2') ? '<span class="label label-danger">Privado</span>' : '<span class="label label-success">Público</span>';
echo '&nbsp;';
echo ($objeto->estado == '1') ? '<span class="label label-default">Borrador</span>' : '<span class="label label-success">Completado</span>';
?>
<script type='text/javascript'>
    var id = '<?php echo $objeto->id; ?>';
    var tabla = '<?php echo $tabla; ?>';
    var modulo = '<?php echo ucfirst($modulo); ?>';
    var nombre = '<?php echo $nombre; ?>';

    $("#btn_privado").on('click', function(e) {
        $("#btn_privado").attr('class', 'btn btn-default btn-xs disabled');

        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/gestion_nivel_estado/privado/'; ?>" + tabla + "/" + id + "/" + modulo + "/" + nombre + "/",
            data: "nivel_estado=privado&tabla=" + tabla + "&id=" + id + "&modulo=" + modulo + "&nombre=" + nombre,
        }).done(function(data) {
            $("#div_nivel_estado").html(data);
        }).fail(function() {
            alert("error: " + id + " " + tabla);
        });
    });

    $("#btn_publico").on('click', function(e) {
        $("#btn_publico").attr('class', 'btn btn-default btn-xs disabled');

        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/gestion_nivel_estado/publico/'; ?>" + tabla + "/" + id + "/" + modulo + "/" + nombre + "/",
            data: "nivel_estado=publico&tabla=" + tabla + "&id=" + id + "&modulo=" + modulo + "&nombre=" + nombre,
        }).done(function(data) {
            $("#div_nivel_estado").html(data);
        }).fail(function() {
            alert("error: " + id + " " + tabla);
        });
    });

    $("#btn_borrador").on('click', function(e) {
        $("#btn_borrador").attr('class', 'btn btn-default btn-xs disabled');

        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/gestion_nivel_estado/borrador/'; ?>" + tabla + "/" + id + "/" + modulo + "/" + nombre + "/",
            data: "nivel_estado=borrador&tabla=" + tabla + "&id=" + id + "&modulo=" + modulo + "&nombre=" + nombre,
        }).done(function(data) {
            $("#div_nivel_estado").html(data);
        }).fail(function() {
            alert("error: " + id + " " + tabla);
        });
    });

    $("#btn_completo").on('click', function(e) {
        $("#btn_completo").attr('class', 'btn btn-default btn-xs disabled');

        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/gestion_nivel_estado/completo/'; ?>" + tabla + "/" + id + "/" + modulo + "/" + nombre + "/",
            data: "nivel_estado=completo&tabla=" + tabla + "&id=" + id + "&modulo=" + modulo + "&nombre=" + nombre,
        }).done(function(data) {
            $("#div_nivel_estado").html(data);
        }).fail(function() {
            alert("error: " + id + " " + tabla);
        });
    });
</script>