<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

       <div class="row">
             <div class="col-md-6">
                 <?php echo DwForm::hidden('subtipo_megaproyecto.id', NULL, $subtipo_megaproyecto->id); ?> 
                <?php echo DwForm::hidden('subtipo_megaproyecto.tipo_megaproyecto_id', NULL, $subtipo_megaproyecto->tipo_megaproyecto_id); ?> 
                <?php echo DwForm::text('subtipo_megaproyecto.nombre', array('class'=>'input-required'), $subtipo_megaproyecto->nombre, 'Nombre'); ?>
            </div>   
            <div class="col-md-6">
            <?php echo DwForm::textarea('subtipo_megaproyecto.descripcion', array('class'=>'input-lower'), $subtipo_megaproyecto->descripcion, 'Descripción'); ?>
            </div>
        </div>            

       <div class="row">
            <div class="form-actions">                   
                <?php echo DwForm::send('Actualizar impacto'); ?>
                <?php echo DwForm::cancel('opcion/subtipo_megaproyecto/listar/'.$tipo_megaproyecto_id); ?>
                <?php echo DwForm::focus('impacto.nombre'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?> 
</div>