<footer class="navbar navbar-inverse navbar-fixed-bottom hidden-xs">
    <div class="container">
        <div class="pull-right hidden-xs">
            <p>Versión: <?php echo APP_VERSION; ?> - Ip: <?php echo Session::has('ip') ? Session::get('ip') : DwUtils::getIp(); ?> - Tiempo: <?php echo number_format(round((microtime(1)-START_TIME),4),4),' seg.'?></p>    
            
                <?php
                    $config = DwConfig::read('config', '', true);
                    $produccion = $config['application']['production'];
                    $database = $config['application']['database'];
                    
                    if($produccion == 'Off')
                    {
                        echo '<p>MODO DESARROLLO --- BD => '.$database.'</p>';
                    }
                ?>
            
        </div>
        <div>
            <p class="visible-xs">&copy; Copyright <?php echo date("Y"); ?>.</p>
            <p class="visible-xs">Todos los derechos reservados.</p>
            <p class="hidden-xs">&copy; Copyright <?php echo date("Y"); ?>. Todos los derechos reservados.</p>
        </div>                
    </div>        
</footer>