<?php ?> 
 <?php echo DwForm::hidden('tituladosi.territorio_id', NULL, $array_titulado_si['territorio_id']); ?>
<?php echo DwForm::hidden('tituladosi.id', NULL, $array_titulado_si['id']); ?>
<div class="col-md-12"> 
                       <div class="row">
                        <div class="col-md-3">                             
                            <?php echo DwForm::text('tituladosi.resolucion_constitucion', array('class'=>'input-lower input-required'), $array_titulado_si['resolucion_constitucion'], 'Resolución constitución'); ?>                          
                        </div>
                        <div class="col-md-3">
                            <label for="tituladosi_area_titulada">Area titulada<span class="req">*</span></label>
                                     <div class="form-group">
                                        <div class="input-group">                                 
                                            <input id="tituladosi_area_titulada" name="tituladosi[area_titulada]" type="number" value="<?php echo $array_titulado_si['area_titulada']; ?>" class="form-control input-lower input-integer input-required" required="required" data-invalid="">                                          
                                          <div class="input-group-addon">ha</div>                                          
                                        </div>
                                      </div>
                        </div>
                           <div class="col-md-6">
                                   <?php echo DwForm::textarea('tituladosi.limite_lindero', array('class'=>'input-lower input-required'), $array_titulado_si['limite_lindero'], 'Límite / lindero'); ?>                            
                        </div>                                                    
                    </div> 
     <div class="row">    
         <?php 
            if($array_titulado_si['documento_constitucion'] == '')
            {
                echo '<div class="col-md-3">';                                
                echo DwForm::upload_V2('documento_constitucion', array('data-to'=>PUBLIC_PATH.'observatorio/territorios/upload/documento_constitucion/', 'data-size'=>5000000, 'data-files'=>'doc', 'data-success'=>'loadDocCon'), 'Adjuntar documento de constitución', 'text_con', 'icon_con');
                echo '</div>  
                      <div class="col-md-9">                        
                         <a id="enlace_documento_con" target="_blank" href="">                            
                         </a>                            
                      </div>';
                echo DwForm::hidden('tituladosi.documento_constitucion', NULL, '');
                            
            }
            else
            {
                echo '<div class="col-md-3">';                                
                echo DwForm::upload_V2('documento_constitucion', array('data-to'=>PUBLIC_PATH.'observatorio/territorios/upload/documento_constitucion/', 'data-size'=>5000000, 'data-files'=>'doc', 'data-success'=>'loadDocCon'), 'Cambiar documento de constitución', 'text_con', 'icon_con');
                echo '</div>';  
                echo '<div class="col-md-9">';                        
                echo '<a id="enlace_documento_con" class="btn btn-info" target="_blank" href="http://dbpacifico.juliomurillo.net/default/public/files/upload/territorio/resolucion/documento_constitucion/'.$array_titulado_si['documento_constitucion'].'">';
                echo '<i class="fa fa-pd-expand fa-eye"></i>Ver documento adjunto</a>';                            
                echo '</div>';
                echo DwForm::hidden('tituladosi.documento_constitucion', NULL, $array_titulado_si['documento_constitucion']);
                                  
            }
         ?>
     </div>
         <script type="text/javascript">
    
    function loadDocCon(result, input) 
    {
        
        $("#tituladosi_documento_constitucion").val(result.name);
        $("#enlace_documento_con").attr('href', 'http://dbpacifico.juliomurillo.net/default/public/files/upload/territorio/resolucion/documento_constitucion/'+result.name);
        $("#enlace_documento_con").attr('class', 'btn btn-info');
        
        //$("#enlace_documento").attr('innerHTML', result.name);
        document.getElementById('enlace_documento_con').innerHTML = '<i class="fa fa-pd-expand fa-eye"></i> Ver documento adjunto - '+result.size;
        document.getElementById('text_con').innerHTML = 'Cambiar documento de constitución';
        $("#icon_con").attr('class', 'fa fa-edit fa-pd-expand');
        }
    
</script>
                      
                <label for="panel_solicitud_ampliacion"><h3 class="panel-title">Solicitud ampliación</h3></label>   
                <div id="panel_solicitud_ampliacion" class="panel panel-default">
                  <div class="panel-body">
                      <div class="row">
                          <div class="col-md-3">
                              
                            <?php echo DwForm::date('tituladosi.solicitud_ampliacion_fecha', array('class'=>'input-required'), substr($array_titulado_si['solicitud_ampliacion_fecha'], 0, 10), 'Fecha de la solicitud'); ?>
                        </div> 
                          <div class="col-md-3">
                              
                                    <?php echo DwForm::text('tituladosi.solicitud_ampliacion_resolucion', array('class'=>'input-lower input-required'), $array_titulado_si['solicitud_ampliacion_resolucion'], 'Resolución'); ?>

                          </div>
                           <div class="col-md-3">
                            <label for="tituladosi_solicitud_ampliacion_area">Area solicitada<span class="req">*</span></label>
                                     <div class="form-group">
                                        <div class="input-group">                                 
                                            <input id="tituladosi_solicitud_ampliacion_area" name="tituladosi[solicitud_ampliacion_area]" type="number" value="<?php echo $array_titulado_si['solicitud_ampliacion_area']?>" class="form-control input-lower input-integer input-required" required="required" data-invalid="">                                          
                                          <div class="input-group-addon">ha</div>                                          
                                        </div>
                                      </div>
                        </div>
                      </div>
                      <div class="row">
                          <div class="col-md-6">
                                
                                   <?php echo DwForm::textarea('tituladosi.solicitud_ampliacion_lindero_limite', array('class'=>'input-lower input-required'), $array_titulado_si['solicitud_ampliacion_lindero_limite'], 'Límite / lindero'); ?>                  
                        </div>
                           <div class="col-md-6">
                                
                                   <?php echo DwForm::textarea('tituladosi.solicitud_ampliacion_observacion', array('class'=>'input-lower input-required'), $array_titulado_si['solicitud_ampliacion_observacion'], 'Observaciones'); ?>                  
                        </div>                          
                      </div>
                      <div class="row">    
         <?php 
            if($array_titulado_si['solicitud_ampliacion_documento'] == '')
            {
                echo '<div class="col-md-4">';                                
                echo DwForm::upload_V2('documento_ampliacion', array('data-to'=>PUBLIC_PATH.'observatorio/territorios/upload/documento_ampliacion/', 'data-size'=>5000000, 'data-files'=>'doc', 'data-success'=>'loadDocSolAmp'), 'Adjuntar documento de solicitud ampliación', 'text_sol_amp', 'icon_sol_amp');
                echo '</div>  
                      <div class="col-md-8">                        
                         <a id="enlace_documento_sol_amp" target="_blank" href="">                            
                         </a>                            
                      </div>';
                echo DwForm::hidden('tituladosi.solicitud_ampliacion_documento', NULL, '');
                            
            }
            else
            {
                echo '<div class="col-md-4">';                                
                echo DwForm::upload_V2('documento_ampliacion', array('data-to'=>PUBLIC_PATH.'observatorio/territorios/upload/documento_ampliacion/', 'data-size'=>5000000, 'data-files'=>'doc', 'data-success'=>'loadDocSolAmp'), 'Cambiar documento de solicitud ampliación', 'text_sol_amp', 'icon_sol_amp');
                echo '</div>';  
                echo '<div class="col-md-8">';                        
                echo '<a id="enlace_documento_sol_amp" class="btn btn-info" target="_blank" href="http://dbpacifico.juliomurillo.net/default/public/files/upload/territorio/resolucion/documento_ampliacion/'.$array_titulado_si['solicitud_ampliacion_documento'].'">';
                echo '<i class="fa fa-pd-expand fa-eye"></i>Ver documento adjunto</a>';                            
                echo '</div>';
                echo DwForm::hidden('tituladosi.solicitud_ampliacion_documento', NULL, $array_titulado_si['solicitud_ampliacion_documento']);
                                  
            }
         ?>
     </div>
                       <script type="text/javascript">
    
    function loadDocSolAmp(result, input) 
    {
        $("#tituladosi_solicitud_ampliacion_documento").val(result.name);
        $("#enlace_documento_sol_amp").attr('href', 'http://dbpacifico.juliomurillo.net/default/public/files/upload/territorio/resolucion/documento_ampliacion/'+result.name);
        $("#enlace_documento_sol_amp").attr('class', 'btn btn-info');
        
        //$("#enlace_documento").attr('innerHTML', result.name);
        document.getElementById('enlace_documento_sol_amp').innerHTML = '<i class="fa fa-pd-expand fa-eye"></i> Ver documento adjunto - '+result.size;
        document.getElementById('text_sol_amp').innerHTML = 'Cambiar documento de solicitud ampliación';
        $("#icon_sol_amp").attr('class', 'fa fa-edit fa-pd-expand');
        }
    
</script>                      
                  </div>
                </div>               
                <label for="panel_solicitud_saneamiento"><h3 class="panel-title">Solicitud saneamiento</h3></label>   
                <div id="panel_solicitud_saneamiento" class="panel panel-default">
                  <div class="panel-body">
                      <div class="row">
                          <div class="col-md-3">
                              
                            <?php echo DwForm::date('tituladosi.solicitud_saneamiento_fecha', array('class'=>'input-required'), substr($array_titulado_si['solicitud_saneamiento_fecha'], 0, 10), 'Fecha de la solicitud'); ?>
                        </div> 
                          <div class="col-md-3">
                              
                                    <?php echo DwForm::text('tituladosi.solicitud_saneamiento_resolucion', array('class'=>'input-lower input-required'), $array_titulado_si['solicitud_saneamiento_resolucion'], 'Resolución'); ?>

                          </div>
                           <div class="col-md-3">
                            <label for="tituladosi_solicitud_saneamiento_area">Area solicitada<span class="req">*</span></label>
                                     <div class="form-group">
                                        <div class="input-group">                                 
                                            <input id="tituladosi_solicitud_saneamiento_area" name="tituladosi[solicitud_saneamiento_area]" type="number" value="<?php echo $array_titulado_si['solicitud_saneamiento_area'];?>" class="form-control input-lower input-integer input-required" required="required" data-invalid="">                                          
                                          <div class="input-group-addon">Hectáreas</div>                                          
                                        </div>
                                      </div>
                        </div>
                      </div>
                      <div class="row">
                          <div class="col-md-6">
                                
                                   <?php echo DwForm::textarea('tituladosi.solicitud_saneamiento_lindero_limite', array('class'=>'input-lower input-required'), $array_titulado_si['solicitud_saneamiento_lindero_limite'], 'Límite / lindero'); ?>                  
                        </div>
                           <div class="col-md-6">
                                
                                   <?php echo DwForm::textarea('tituladosi.solicitud_saneamiento_observacion', array('class'=>'input-lower input-required'), $array_titulado_si['solicitud_saneamiento_observacion'], 'Observaciones'); ?>                  
                        </div>
                          
                      </div>
                      <div class="row">    
         <?php 
            if($array_titulado_si['solicitud_saneamiento_documento'] == '')
            {
                echo '<div class="col-md-4">';                                
                echo DwForm::upload_V2('documento_saneamiento', array('data-to'=>PUBLIC_PATH.'observatorio/territorios/upload/documento_saneamiento/', 'data-size'=>5000000, 'data-files'=>'doc', 'data-success'=>'loadDocSolSan'), 'Adjuntar documento de saneamiento', 'text_sol_san', 'icon_sol_san');
                echo '</div>  
                      <div class="col-md-8">                        
                         <a id="enlace_documento_sol_san" target="_blank" href="">                            
                         </a>                            
                      </div>';
                echo DwForm::hidden('tituladosi.solicitud_saneamiento_documento', NULL, '');
                            
            }
            else
            {
                echo '<div class="col-md-4">';                                
                echo DwForm::upload_V2('documento_saneamiento', array('data-to'=>PUBLIC_PATH.'observatorio/territorios/upload/documento_saneamiento/', 'data-size'=>5000000, 'data-files'=>'doc', 'data-success'=>'loadDocSolSan'), 'Cambiar documento de solicitud saneamiento', 'text_sol_san', 'icon_sol_san');
                echo '</div>';  
                echo '<div class="col-md-8">';                        
                echo '<a id="enlace_documento_sol_san" class="btn btn-info" target="_blank" href="http://dbpacifico.juliomurillo.net/default/public/files/upload/territorio/resolucion/documento_saneamiento/'.$array_titulado_si['solicitud_saneamiento_documento'].'">';
                echo '<i class="fa fa-pd-expand fa-eye"></i>Ver documento adjunto</a>';                            
                echo '</div>';
                echo DwForm::hidden('tituladosi.solicitud_saneamiento_documento', NULL, $array_titulado_si['solicitud_saneamiento_documento']);
                                  
            }
         ?>
     </div>
                      <script type="text/javascript">
    
    function loadDocSolSan(result, input) 
    {
        $("#tituladosi_solicitud_saneamiento_documento").val(result.name);
        $("#enlace_documento_sol_san").attr('href', 'http://dbpacifico.juliomurillo.net/default/public/files/upload/territorio/resolucion/documento_saneamiento/'+result.name);
        $("#enlace_documento_sol_san").attr('class', 'btn btn-info');
        
        //$("#enlace_documento").attr('innerHTML', result.name);
        document.getElementById('enlace_documento_sol_san').innerHTML = '<i class="fa fa-pd-expand fa-eye"></i> Ver documento adjunto - '+result.size;
        document.getElementById('text_sol_san').innerHTML = 'Cambiar documento de solicitud saneamiento';
        $("#icon_sol_san").attr('class', 'fa fa-edit fa-pd-expand');
        }
    
</script>
                  </div>
                </div>                                                   
                 
  </div>
 
<?php //echo time(); ?>