<div class="btn-toolbar btn-toolbar-top">
    <div class="row">
        <div class="btn-actions">
            <?php //echo DwHtml::button("afectacion/megaproyectos/agregar_empleo/$obj_territorio->id/$obj_territorio->nombre/$obj_territorio->tipo/$key/", 'agregar empleo', array('class' => 'btn-success'), 'fa-check-square-o', APP_AJAX);
            //echo DwHtml::button("afectacion/megaproyectos/agregar_accion_seguimiento_control/$megaproyecto->id/$megaproyecto->nombre/$megaproyecto->clase_megaproyecto/$key/", 'agregar accion seguimiento control', array('class' => 'btn-success'), 'fa-check-square-o', APP_AJAX);
            ?>
        </div>
    </div>
</div>
<table class="table table-bordered table-hover table-striped table-condensed table-responsive">
    <thead>
        <tr>
            <th>NUM</th>
            <th>NOMBRE ORGANIZACIÓN</th>
            <th>REPRESENTANTE LEGAL</th>
            <th class="btn-actions text-center">ESTADO</th>
            <th class="btn-actions col-blocked text-center">OPCIONES</th>
        </tr>
    </thead>
    <tbody>
        <?php
        $contador_organizacion = 1;
        foreach ($organizacions as $organizacion) : ?>
            <?php $key_show = Security::setKey($organizacion->id, 'show_organizacion'); ?>
            <?php $key_upd = Security::setKey($organizacion->id, 'upd_organizacion'); ?>
            <tr>
                <td><?php echo $contador_organizacion; ?></td>
                <td><?php echo $organizacion->nombre; ?></td>
                <td><?php echo $organizacion->nombre_representante_legal; ?></td>
                <td class="btn-actions"><?php View::partial('nivel_estado/ver', false, array('nivel' => $organizacion->nivel, 'estado' => $organizacion->estado)); ?>
                <td class="btn-actions">
                    <?php View::partial(
                        'opcion/ver',
                        false,
                        array(
                            'elemento' => 'organizacion',
                            "nombre" => $organizacion->nombre,
                            "url_ver" => "gestion_territorial/gestion_tcur/ver_organizacion/$key_show/$key/$order/$page/",
                            "url_editar" => NULL,
                            "url_eliminar" => NULL
                        )
                    ); ?>
                </td>
            </tr>
            <?php $contador_organizacion++; ?>
        <?php endforeach; ?>
    </tbody>
</table>
<br>