<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>
    
     
    <ul class="nav nav-tabs nav-justified hidden-xs">
        <li class="active"><a href="#tab1" data-toggle="tab">Información general</a></li>
        <li class="disabled"><a href="#">Afectaciones</a></li>              
    </ul>
    <ul class="nav nav-tabs nav-justified visible-xs">    
        <li class="tab-pane active"><a href="#tab1" data-toggle="tab">Información general</a></li>
        <li class="tab-pane <?php echo $tab_2_active; ?>"><a href="#tab2" data-toggle="tab">Afectaciones</a></li>                
    </ul>
    
    
    <div class="tab-content">
        <div class="tab-pane active" id="tab1">
            <div class="row">
            <div class="col-md-12">
                <div class="row">
                           <div class="col-md-12">
                               <label for="panel_ubicacion_proyecto"><h3 class="panel-title">Ubicación del cultivo ilícito</h3></label>
                            <div id="panel_ubicacion_proyecto" class="panel panel-default">
                                <div class="panel-body">
                                
                      
                      <div class="row">
                        <div class="col-md-3" id="div_departamento"> 
                            <?php echo DwForm::dbSelect('caso.departamento_id', 'nombre', array('observatorio/departamento', 'getListadoDepartamentoDBS', Departamento::ACTIVO), NULL, array('class'=>'input-required'), NULL, 'Departamento'); ?>                           
                        </div>
                        <div class="col-md-3" id="div_municipio">                    
                            <?php echo DwForm::dbSelect('caso.municipio_id', 'nombre', array('observatorio/municipio', 'getMunicipioPorDepartamento',  ''), NULL, array('class' => 'input-required'), NULL, 'Municipio'); ?>                        </div>
                       <div class="col-md-6" id="div_territorio">                                                
                           <?php echo DwForm::dbSelect('caso.territorio_id', 'nombre', array('observatorio/territorio_municipio', 'getTerritoriosByMunicipioIdSelect', ''), NULL, array('class' => ''), NULL, 'Territorio'); ?>
                        </div>  
                          
                </div>
                      
                                </div>
                            </div>                           
                        </div>                          
                      </div>
                <div class="row">
                    <div class="col-md-3">
                        <?php echo DwForm::dbSelect('cultivo_ilicito.tipo_cultivo_id', 'nombre', array('opcion/tipo_cultivo', 'getListadoTipoCultivoDBS', ''), NULL, array('class'=>'input-required'), NULL, 'Seleccione el tipo de cultivo'); ?>
                    </div>                            
                    <div class="col-md-3">
                            <label for="area">Área del cultivo<!--<span class="req">*</span>--></label>
                                     <div class="form-group">
                                        <div class="input-group">                                 
                                            <input id="area" name="cultivo_ilicito[area]" type="text" class="form-control formato_punto_coma" required="" data-invalid="">                                          
                                          <div class="input-group-addon">hectareas</div>                                          
                                        </div>
                                      </div>
                        </div>
                     
                     <div class="col-md-6">
                 <label for="panel_promotores">Promotores del cultivo</label>   
                <div id="panel_promotores" class="panel panel-default">
                  <div class="panel-body">
                       <div class="row">
                        <div class="col-md-4">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.promo_guerrilla', '1', NULL, NULL, 'GUERRILLA'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.promo_paramilitar', '1', NULL, NULL, 'PARAMILITARES'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.promo_otro', '1', NULL, NULL, 'OTROS'); ?>
                                </div>
                            </div>                              
                        </div>                 
                    </div>                                        
                  </div>
               </div>
            </div>
            

                </div>    
                <div class="row">
                    <div class="col-md-12">
                        <label for="panel_participacion"><h3 class="panel-title">Participación en el cultivo</h3></label>   
                <div id="panel_participacion" class="panel panel-default">
                  <div class="panel-body">
                       <div class="row">

                                          
                               <div class="col-md-4">  
                                    <?php echo DwForm::select('cultivo_ilicito.part_comunidad', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, '¿La comunidad participa en el cultivo?'); ?>
                               </div>
                            
                            
                                
                                <div id="div_tipo_part_comunidad" class="col-md-4">
                 <label for="panel_tipo_part_comunidad">Tipo de participación de la comunidad</label>   
                <div id="panel_tipo_part_comunidad" class="panel panel-default">
                  <div class="panel-body">
                       <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.tipo_part_com_cultivador', '1', NULL, NULL, 'CULTIVADORES'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.tipo_part_com_raspachin', '1', NULL, NULL, 'RASPACHINES'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.tipo_part_com_procesador', '1', NULL, NULL, 'PROCESADORES'); ?>
                                </div>
                            </div>                              
                        </div>                 
                    </div>                                        
                  </div>
               </div>
            </div>
                                
                       </div> 
                                                    
                      
                           
                           
                           <!-- ------------------------------ -->
                           
                            <div class="row">
                               <div class="col-md-4">  
                                    <?php echo DwForm::select('cultivo_ilicito.part_otro', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, '¿Otros participan en el cultivo?'); ?>
                               </div>
                           
                                <div id="div_tipo_part_otro" class="col-md-4">
                 <label for="panel_tipo_part_otro">Tipo de participación de otros</label>   
                <div id="panel_tipo_part_otro" class="panel panel-default">
                  <div class="panel-body">
                       <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.tipo_part_otr_cultivador', '1', NULL, NULL, 'CULTIVADORES'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.tipo_part_otr_raspachin', '1', NULL, NULL, 'RASPACHINES'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.tipo_part_otr_procesador', '1', NULL, NULL, 'PROCESADORES'); ?>
                                </div>
                            </div>                              
                        </div>                 
                    </div>                                        
                  </div>
               </div>
            </div>       
                                
                                <div id="div_part_otro_quien" class="col-md-4">
                                   <?php echo DwForm::textarea('cultivo_ilicito.part_otro_quien', array('class'=>'input-lower'), NULL, '¿Quienes son los otros participantes?'); ?>
                                </div>                                 
                               
            </div>                                                                                  
        
                           
                           
                           
                           
                           
                           
                    </div>                                        
                  </div>
               </div>
            </div>
                
                <label for="panel_erradicacion"><h3 class="panel-title">Erradicación</h3></label>                
               <div id="panel_erradicacion" class="panel panel-default">
                  <div class="panel-body">
                   <div class="row">
                     <div class="col-md-6">  
                        <?php echo DwForm::select('cultivo_ilicito.tipo_erradicacion', array(''=>'Seleccione', 'ASPERSION AEREA'=>'ASPERSIÓN AÉREA', 'ERRADICACION MANUAL'=>'ERRADICACIÓN MANUAL'), array('class'=>''), NULL, 'Tipo de erradicación'); ?>
                    </div>  
                       <div class="col-md-6">
                            <label for="area_erradicacion">Área<!--<span class="req">*</span>--></label>
                                     <div class="form-group">
                                        <div class="input-group">                                 
                                            <input id="area_erradicacion" name="cultivo_ilicito[area_erradicacion]" type="text" class="form-control formato_punto_coma" required="" data-invalid="">                                          
                                          <div class="input-group-addon">hectareas</div>                                          
                                        </div>
                                      </div>
                        </div>
                </div>
                      <div class="row"> 
                          <div class="col-md-6">
                <label for="panel_modalidad">Modalidad</label>   
                <div id="panel_modalidad" class="panel panel-default">
                  <div class="panel-body">
                       <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::select('cultivo_ilicito.ejecucion_directa', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, 'Ejecución directa'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::select('cultivo_ilicito.contratada', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, 'Contratada'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div id="div_contratada_quienes" class="col-md-12">
                                    <?php echo DwForm::textarea('cultivo_ilicito.contratada_quienes', array('class'=>'input-lower'), NULL, '¿Quienes fueron contratados?'); ?>
                                </div>
                            </div>                              
                        </div>                 
                    </div>                                        
                  </div>
               </div>
                          </div>
                      <div class="col-md-6">
                          <?php echo DwForm::select('cultivo_ilicito.consulta_previa', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, 'Consulta previa'); ?>
                      </div>
                      </div>                     
                                           
                  </div>
               </div>
            </div>
      
            <div class="col-md-12">               
               <label for="panel_fuente"><h3 class="panel-title">Fuente(s) de la información</h3></label>               
                 <div id="panel_fuente" class="panel panel-default">
                     <div class="panel-body">
                        <?php View::partial('fuentes/agregar', false, NULL); ?>
                    </div>                    
                </div>
            </div> 
           
                          
                    
        </div>                        
             <div class="row">
            <div class="form-actions">
                <?php echo DwForm::sendContinue('Continuar'); ?>
                <?php echo DwForm::cancel(); ?>
                <?php //echo DwForm::focus('caso.titulo'); ?>
            </div>
        </div>
        </div>
                        
<!--      //////////////////////////////////  SEGUNDA PESTAÑA-->
 <div class="tab-pane <?php echo $tab_2_active; ?>" id="tab2">
           
    </div> 
    </div>
     <?php echo DwForm::close(); ?> 
</div>




    
    <script type='text/javascript'>
    $(".formato_punto_coma").priceFormat(
    {
        prefix: '',
        centsLimit: 2,
        centsSeparator: ',',
        thousandsSeparator: '.'
    }); 
    
    $(".formato_punto").priceFormat(
    {
        prefix: '',
        centsLimit: 0,
        centsSeparator: ',',
        thousandsSeparator: '.'
    }); 
        
 $("#caso_departamento_id").on('change', function(e) {
            var departamento_id = $('#caso_departamento_id').val();
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_select_municipios/'; ?>"+departamento_id+"/caso.municipio_id/Municipio/no/",
                data: "departamento_id=" + departamento_id + "&field=caso.municipio_id&label=Municipio&input_required=no",
            }).done(function(data) {
                
                $("#div_municipio").html(data);
                $("#caso_municipio_id").focus();
                $('#caso_territorio_id').val('');
            }).fail(function() {
                alert("error");
            });
        });
        
        $("#caso_municipio_id").on('change', function(e) {
            var municipio_id = $('#caso_municipio_id').val();
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_select_territorios_municipio/'; ?>"+municipio_id+"/caso.territorio_id/Territorio/",
                data: "departamento_id=" + municipio_id + "&field=caso.territorio_id&label=Territorio",
            }).done(function(data) {
                $("#div_territorio").html(data);
                $("#caso_territorio_id").focus();
            }).fail(function() {
                alert("error");
            });
        });
        
                  
       if($('#cultivo_ilicito_part_comunidad').val() == 'SI')
        { $('#div_tipo_part_comunidad').show();
        }else{$('#div_tipo_part_comunidad').hide();}
              
        $("#cultivo_ilicito_part_comunidad").change(
        function(){
                var si_no 	=	$('#cultivo_ilicito_part_comunidad').val();
                if( si_no == 'SI')
                    {                        
                        $('#div_tipo_part_comunidad').show();                   
                        //$('#cultivo_ilicito_otra_actividad_cual').focus(); 
                    }
                    else
                    {
                       $('#div_tipo_part_comunidad').hide();
                       //$('#cultivo_ilicito_otra_actividad_cual').val('');
                    }

        });
        
        if($('#cultivo_ilicito_part_otro').val() == 'SI')
        { $('#div_tipo_part_otro').show();
            $('#div_part_otro_quien').show();
        }else{$('#div_tipo_part_otro').hide();
        $('#div_part_otro_quien').hide();}
              
        $("#cultivo_ilicito_part_otro").change(
        function(){
                var si_no 	=	$('#cultivo_ilicito_part_otro').val();
                if( si_no == 'SI')
                    {                        
                        $('#div_tipo_part_otro').show(); 
                        $('#div_part_otro_quien').show();
                        //$('#cultivo_ilicito_otra_actividad_cual').focus(); 
                    }
                    else
                    {
                       $('#div_tipo_part_otro').hide();
                       $('#div_part_otro_quien').hide();
                       //$('#cultivo_ilicito_otra_actividad_cual').val('');
                    }

        });
        
        
        
        if($('#cultivo_ilicito_contratada').val() == 'SI')
        { $('#div_contratada_quienes').show();
            
        }else{$('#div_contratada_quienes').hide();
        }
              
        $("#cultivo_ilicito_contratada").change(
        function(){
                var si_no 	=	$('#cultivo_ilicito_contratada').val();
                if( si_no == 'SI')
                    {                        
                        $('#div_contratada_quienes').show();                         
                        $('#cultivo_ilicito_contratada_quienes').focus(); 
                    }
                    else
                    {
                       $('#div_contratada_quienes').hide();                       
                    }

        });
        
        
        
        
</script>
