<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

        <div class="row">
             <div class="col-md-6">
                        <?php echo DwForm::text('asociacion_cabildo_zonal.nombre', array('class'=>'input-required'), $asociacion_cabildo_zonal->nombre, 'Nombre'); ?>
                    </div>             
        </div>           

       <div class="row">
            <div class="form-actions">                   
                <?php echo DwForm::send('Actualizar Asociación cabildo zonal'); ?>
                <?php echo DwForm::cancel('opcion/asociacion_cabildo_zonal/listar/'); ?>
                <?php echo DwForm::focus('asociacion_cabildo_zonal.nombre'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?> 
</div>