       <div class="row">
                           <div class="col-md-12">
                            <label for="panel_edad">Edad</label>
                            <div id="panel_edad" class="panel panel-default">
                                <div class="panel-body">
                                 <div class="row">
                                    <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e0_4', array('class'=>'input-integer'), NULL, '0 - 4'); ?>
                                    </div>
                                    <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e5_9', array('class'=>'input-integer'), NULL, '5 - 9'); ?>
                                    </div>
                                       <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e10_14', array('class'=>'input-integer'), NULL, '10 - 14'); ?>
                                    </div>
                                       <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e15_19', array('class'=>'input-integer'), NULL, '15 - 19'); ?>
                                    </div>
                                     <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e20_24', array('class'=>'input-integer'), NULL, '20 - 24'); ?>
                                    </div>
                                     <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e25_29', array('class'=>'input-integer'), NULL, '25 - 29'); ?>
                                    </div>
                                </div>        
                                    <div class="row">                               
                                       <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e30_34', array('class'=>'input-integer'), NULL, '30 - 34'); ?>
                                    </div>
                                       <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e35_39', array('class'=>'input-integer'), NULL, '35 - 39'); ?>
                                    </div>
                                         <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e40_44', array('class'=>'input-integer'), NULL, '40 - 44'); ?>
                                    </div>
                                    <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e45_49', array('class'=>'input-integer'), NULL, '45 - 49'); ?>
                                    </div>
                                       <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e50_54', array('class'=>'input-integer'), NULL, '50 - 54'); ?>
                                    </div>
                                       <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e55_59', array('class'=>'input-integer'), NULL, '55 - 59'); ?>
                                    </div>
                                </div>   
                                   
                                    <div class="row">
                                    <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e60_64', array('class'=>'input-integer'), NULL, '60 - 64'); ?>
                                    </div>
                                    <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e65_69', array('class'=>'input-integer'), NULL, '65 - 69'); ?>
                                    </div>
                                       <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e70_74', array('class'=>'input-integer'), NULL, '70 - 74'); ?>
                                    </div>
                                       <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e75_79', array('class'=>'input-integer'), NULL, '75 - 79'); ?>
                                    </div>
                                        <div class="col-md-2">
                                        <?php echo DwForm::number('poblacion.e80_mas', array('class'=>'input-integer'), NULL, '80 ó mas'); ?>
                                    </div>
                                </div> 
                                    
                                </div>
                            </div>
                           
                        </div>
                          
                      </div>