<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

        <div class="row">
             <div class="col-md-6">
                        <?php echo DwForm::text('asociacion_cabildo_regional.nombre', array('class'=>'input-required'), NULL, 'Nombre'); ?>
                    </div>             
        </div>           

        <div class="row">
            <div class="form-actions">                   
                <?php echo DwForm::send('Guardar Asociación cabildo regional'); ?>
                <?php echo DwForm::cancel('opcion/asociacion_cabildo_regional/listar'); ?>
                <?php echo DwForm::focus('asociacion_cabildo_regional.nombre'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?> 
</div>