<?php DwForm::open() ?>
<div class="modal fade" id="modal_editar_localidad">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Editar <?php echo $Localidad->tipo;?></h4>
                  </div>
                  <div class="modal-body">
                    <?php echo DwForm::text('localidad.editar_nombre', array('class'=>'', 'onkeyup'=>'validarEditarNombreLocalidad()'), $Localidad->nombre, '<div id=\'titulo_editar_localidad\'>Nombre</div>'); ?>                 
                  </div>
                  <div class="modal-footer">
                    <button id="btn-cancelar-guardar-editar-localidad" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button id="btn-guardar-editar-localidad" type="button" class="btn btn-primary" onclick="guardarEditarLocalidad()" data-loading-text="Actualizando...">Guardar Cambios</button>
                  </div>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->