<?php View::flash(); ?>
<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::hidden('tipo', NULL, 'comunidad_negra') ?>
    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions">
                <?php //echo DwHtml::button("gestion_territorial/gestion_tccn/index_agregar_territorio/comunidad_negra", 'agregar', array('class' => 'btn-success'), 'fa-check-square-o', APP_AJAX); ?>
            </div>            
        </div>
    </div>

    <div class="container-overflow">

        <table class="datatable table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th data-search="nombre" data-order="nombre">NOMBRE</th>
                    <th class="col-hidden" data-order="cant_consejo_reg">CONSEJOS</th>
                    <th class="col-hidden" data-order="titulado">TITULADO</th>
                    <th class="col-hidden" data-search="departamento" data-order="departamento">DEPARTAMENTO</th>
                    <th class="btn-actions col-blocked text-center">OPCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php $num++; ?>
                <?php foreach($territorios as $territorio): ?>
                    <?php $key_show = Security::setKey($territorio->id, 'show_territorio'); ?>
                    <?php $key_upd = Security::setKey($territorio->id, 'upd_territorio'); ?>
                    <?php $key_inac = Security::setKey($territorio->id, 'inactivar_territorio'); ?>
                    <?php $key_reac = Security::setKey($territorio->id, 'reactivar_territorio'); ?>
                    <?php $key_del = Security::setKey($territorio->id, 'eliminar_territorio'); ?>
                    <tr>
                        <td><?php echo $num++; ?></td>
                        <td><?php echo $territorio->nombre; ?></td>
                        <td><?php echo $territorio->cant_consejo_reg; ?></td>
                        <td><?php echo $territorio->titulado; ?></td>                        
                        <td><?php echo $territorio->departamento; ?></td> 
                        <td class="btn-actions">
                            <?php                                
                                echo DwHtml::buttonTableIcons('Ver gestión territorial', "gestion_territorial/gestion_tccn/ver/$key_show/1/$order/$page/", null, 'info', array('fa-group','fa-eye')); ?>
                            <?php echo DwHtml::buttonTableIcons('Modificar gestión territorial', "gestion_territorial/gestion_tccn/editar/$key_upd/1/$order/$page/", null, 'warning', array('fa-group','fa-edit')); ?>
                            <?php //echo DwHtml::buttonTable('Agregar comunidad', "gestion_territorial/gestion_tccn/agregar_comunidad/$territorio->id/$territorio->nombre/$territorio->tipo/", null, 'success', 'fa-plus'); ?>
                            <?php 
                                if(Session::get('perfil') == 'ADMINISTRADOR' || Session::get('perfil') == 'Super Usuario')
                                {
                                    //echo DwHtml::buttonTable('Eliminar territorio', "gestion_territorial/gestion_tccn/eliminar/$key_del/listar_territorio_cn/$order/page.$page/", array('class'=>'js-confirm', 'msg-title'=>'Eliminar territorio', 'msg'=>'Está seguro de eliminar este territorio? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'fa-ban');
                                }
                            ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

</div>