<?php View::flash(); ?>

<div class="container shell-view">
    <?php View::process_estado_nivel('cooperacion', $cooperacion, $page_module, $page_title, $set_title); ?>

    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">Información General</a></li>
        <li><a data-toggle="tab" href="#menu1">Daños</a></li>
        <li><a data-toggle="tab" href="#menu2">Fuente de la información</a></li>
    </ul>

    <div class="tab-content">
        <div id="home" class="tab-pane fade in active">

            <?php echo DwForm::open(); ?>

            <div class="row">
                <div class="col-md-12">
                    <label for="panel_info_basica">
                        <h3 class="panel-title"></h3>
                    </label>
                    <div id="panel_info_basica" class="panel panel-default">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-3">
                                    <?php echo DwForm::hidden('cooperacion.id', NULL, NULL); ?>
                                    <?php echo DwForm::hidden('cooperacion.afectacion_id', NULL, NULL); ?>
                                    <?php echo DwForm::text('cooperacion.nombre_clase_cooperacion', array('class' => 'input-required'), NULL, 'Nombre cooperación'); ?>
                                </div>
                                <div class="col-md-3">
                                    <?php echo DwForm::dbSelect('cooperacion.clase_cooperacion_id', 'nombre', array('opcion/clase_cooperacion', 'getListadoClaseCooperacionDBS', ''), NULL, array('class' => 'input-required'), NULL, 'Cooperación'); ?>
                                </div>
                                <div class="col-md-3">
                                    <?php echo DwForm::text('cooperacion.procedencia_clase_cooperacion', array('class' => ''), NULL, 'Procedencia cooperación'); ?>
                                </div>
                                <div class="col-md-9">
                                    <div id="div_municipiosd"></div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <?php echo DwForm::dbSelect('cooperacion.tipo_cooperacion_id', 'nombre', array('opcion/tipo_cooperacion', 'getListadoTipoCooperacionDBS', ''), NULL, array('class' => 'input-required'), NULL, 'Tipo de cooperación'); ?>
                                </div>
                                <div class="col-md-6">
                                    <?php echo DwForm::text('cooperacion.nombre_tipo_cooperacion', array('class' => ''), NULL, 'Nombre tipo de cooperación'); ?>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <?php echo DwForm::textarea('cooperacion.descripcion', array('class' => 'input-lower', 'rows' => '10'), NULL, 'Descripción'); ?>
                                </div>
                                <div class="col-md-6">

                                    <div class="row">
                                        <div class="col-md-12">
                                            <label for="panel_municipio">Tipo de proyectos</label>
                                            <div id="panel_municipio" class="panel panel-default">
                                                <div class="panel-body">
                                                    <div class="col-md-12">
                                                        <?php echo DwForm::dbCheckId('tipo_proyecto', 'nombre', array('opcion/tipo_proyecto_cooperacion', 'getListadoTipoProyectoCooperacionDBS', '1'), array('onchange' => 'validarTipoProyectoOtro()'), $array_tipo_proyecto); ?>
                                                        <div id="div_cooperacion_tipo_proyecto_cooperacion_otro_descripcion" style="display:none;">
                                                            <?php echo DwForm::text('cooperacion.tipo_proyecto_cooperacion_otro_descripcion', array('onkeyup' => ''), NULL, 'Descripción Otro<span class="req">*</span>'); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <label for="panel_operadores">Operadores</label>
                                            <div id="panel_operadores" class="panel panel-default">
                                                <div class="panel-body">
                                                    <div class="col-md-12">
                                                        <?php echo DwForm::dbCheckId('operador', 'nombre', array('opcion/operador_cooperacion', 'getListadoOperadorCooperacionDBS', ''), array('onchange' => 'validarOperadorOtro()'), $array_operador); ?>
                                                        <div id="div_cooperacion_operador_cooperacion_otro_descripcion" style="display:none;">
                                                            <?php echo DwForm::text('cooperacion.operador_cooperacion_otro_descripcion', array('onkeyup' => ''), NULL, 'Descripción Otro<span class="req">*</span>'); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>


                                    </div>
                                </div>


                            </div>

                            <div class="row">
                                <div class="col-md-3">
                                    <?php echo DwForm::date('cooperacion.periodo_inicia', array('class' => ''), NULL, 'Fecha en que inicia la cooperación'); ?>
                                </div>
                                <div class="col-md-3">
                                    <?php echo DwForm::date('cooperacion.periodo_fin', array('class' => ''), NULL, 'Fecha en que finaliza la cooperación'); ?>
                                </div>
                                <div class="col-md-3">
                                    <?php echo DwForm::select('cooperacion.moneda_monto_inversion', array('' => '- SELECCIONE -', '$' => '$ - PESOS', 'US' => 'US - DOLARES', '€' => '€ - EUROS'), array('class' => ''), NULL, 'Moneda monto de inversión') ?>
                                </div>
                                <div class="col-md-3">
                                    <?php echo DwForm::text('cooperacion.monto_inversion', array('class' => 'input-money'), number_format($cooperacion->monto_inversion, 2, '.', ','), 'Monto de inversión'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <?php View::partial(
                                    'ubicacion/editar',
                                    false,
                                    array(
                                        'ubicaciones' => $ubicaciones,
                                        'afectacion_id' => $cooperacion->afectacion_id,
                                        'titulo' => 'de la cooperación'
                                    )
                                );
                                ?>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-actions">
                    <?php echo DwForm::send('Guardar desarrollo normativo'); ?>
                    <?php echo DwForm::cancel('afectacion/cooperacion/listar/'); ?>
                    <?php echo DwForm::focus('cooperacion.nombre'); ?>
                </div>
            </div>

           

        </div>
        <div id="menu1" class="tab-pane fade">
            <?php View::partial(
                'danos/editar',
                false,
                array(
                    'AfectacionDanoTerritorio' => $AfectacionDanoTerritorio,
                    'nombre_tabla' => 'cooperacion',
                    'afectacion_id' => $cooperacion->afectacion_id
                )
            );
            ?>
        </div>
        <div id="menu2" class="tab-pane fade">
            <label for="panel_fuente">
                <h3 class="panel-title">Fuente(s) de la información</h3>
            </label>
            <div id="panel_fuente" class="panel panel-default">
                <div class="panel-body">
                    <?php View::partial('fuentes/editar', false, array('fuentes' => $fuentes)); ?>
                </div>
            </div>
        </div>
        <?php echo DwForm::close(); ?>
    </div>


    <script type='text/javascript'>
    validarOperadorOtro();
    validarTipoProyectoOtro();
        function validarOperadorOtro() {
            var operador = false;
            var valor = '';
            $('[name="operador[]"]:checked').each(function() {
                valor = $(this).val();
                if (valor === '4') {
                    operador = true;
                }
            });
            if (operador) {
                $("#div_cooperacion_operador_cooperacion_otro_descripcion").show();
                $("#cooperacion_operador_cooperacion_otro_descripcion").focus();
            } else {
                $("#div_cooperacion_operador_cooperacion_otro_descripcion").hide();
                $("#cooperacion_operador_cooperacion_otro_descripcion").val('');
            }
        }

        function validarTipoProyectoOtro() {
            var tipo_proyecto = false;
            var valor = '';
            $('[name="tipo_proyecto[]"]:checked').each(function() {
                valor = $(this).val();
                if (valor === '9') {
                    tipo_proyecto = true;
                }
            });
            if (tipo_proyecto) {
                $("#div_cooperacion_tipo_proyecto_cooperacion_otro_descripcion").show();
                $("#cooperacion_tipo_proyecto_cooperacion_otro_descripcion").focus();
            } else {
                $("#div_cooperacion_tipo_proyecto_cooperacion_otro_descripcion").hide();
                $("#cooperacion_tipo_proyecto_cooperacion_otro_descripcion").val('');
            }
        }

        $("#cooperacion_departamento_id").change(function() {
            var regiones_id = $('#cooperacion_departamento_id').val();
            var departamento_id = $('#cooperacion_departamento_id').val();
            var titulo_panel = 'Seleccione el (los) municipio(s) que tienen cobertura de esta cooperación';
            //var departamento_nombre =	$('#cooperacion_departamento_id').attr('id');
            var departamento_nombre = $("#cooperacion_departamento_id option:selected").attr('texto');
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_check_municipios/'; ?>" + departamento_id + "/" + departamento_nombre + "/" + titulo_panel + "/",
                async: true,
                data: "regiones_id=" + regiones_id,
                success: function(html) {
                    $("#div_municipios").html(html);
                }
            });
        });

        $("#cooperacion_monto_inversion").priceFormat({
            prefix: '',
            centsLimit: 2,
            centsSeparator: '.',
            thousandsSeparator: ','
        });
    </script>
</div>